// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proj/commodity.proto

package projpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Commodity with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Commodity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Commodity with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommodityMultiError, or nil
// if none found.
func (m *Commodity) ValidateAll() error {
	return m.validate(true)
}

func (m *Commodity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for XId

	// no validation rules for Url

	// no validation rules for Title

	for idx, item := range m.GetMedias() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CommodityValidationError{
						field:  fmt.Sprintf("Medias[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CommodityValidationError{
						field:  fmt.Sprintf("Medias[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CommodityValidationError{
					field:  fmt.Sprintf("Medias[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Brand

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for Status

	for idx, item := range m.GetChances() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CommodityValidationError{
						field:  fmt.Sprintf("Chances[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CommodityValidationError{
						field:  fmt.Sprintf("Chances[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CommodityValidationError{
					field:  fmt.Sprintf("Chances[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for UserId

	// no validation rules for CreatedAt

	// no validation rules for Character

	// no validation rules for PackagingAttributes

	if all {
		switch v := interface{}(m.GetExtra()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommodityValidationError{
					field:  "Extra",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommodityValidationError{
					field:  "Extra",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExtra()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommodityValidationError{
				field:  "Extra",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommodityMultiError(errors)
	}

	return nil
}

// CommodityMultiError is an error wrapping multiple validation errors returned
// by Commodity.ValidateAll() if the designated constraints aren't met.
type CommodityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommodityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommodityMultiError) AllErrors() []error { return m }

// CommodityValidationError is the validation error returned by
// Commodity.Validate if the designated constraints aren't met.
type CommodityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommodityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommodityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommodityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommodityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommodityValidationError) ErrorName() string { return "CommodityValidationError" }

// Error satisfies the builtin error interface
func (e CommodityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommodity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommodityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommodityValidationError{}

// Validate checks the field values on CommodityList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CommodityList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommodityList with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommodityListMultiError, or
// nil if none found.
func (m *CommodityList) ValidateAll() error {
	return m.validate(true)
}

func (m *CommodityList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CommodityListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CommodityListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CommodityListValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CommodityListMultiError(errors)
	}

	return nil
}

// CommodityListMultiError is an error wrapping multiple validation errors
// returned by CommodityList.ValidateAll() if the designated constraints
// aren't met.
type CommodityListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommodityListMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommodityListMultiError) AllErrors() []error { return m }

// CommodityListValidationError is the validation error returned by
// CommodityList.Validate if the designated constraints aren't met.
type CommodityListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommodityListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommodityListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommodityListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommodityListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommodityListValidationError) ErrorName() string { return "CommodityListValidationError" }

// Error satisfies the builtin error interface
func (e CommodityListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommodityList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommodityListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommodityListValidationError{}

// Validate checks the field values on Chance with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Chance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Chance with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ChanceMultiError, or nil if none found.
func (m *Chance) ValidateAll() error {
	return m.validate(true)
}

func (m *Chance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTargetAudience()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChanceValidationError{
					field:  "TargetAudience",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChanceValidationError{
					field:  "TargetAudience",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTargetAudience()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChanceValidationError{
				field:  "TargetAudience",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetSellingPoints() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChanceValidationError{
						field:  fmt.Sprintf("SellingPoints[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChanceValidationError{
						field:  fmt.Sprintf("SellingPoints[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChanceValidationError{
					field:  fmt.Sprintf("SellingPoints[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Index

	if len(errors) > 0 {
		return ChanceMultiError(errors)
	}

	return nil
}

// ChanceMultiError is an error wrapping multiple validation errors returned by
// Chance.ValidateAll() if the designated constraints aren't met.
type ChanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChanceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChanceMultiError) AllErrors() []error { return m }

// ChanceValidationError is the validation error returned by Chance.Validate if
// the designated constraints aren't met.
type ChanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChanceValidationError) ErrorName() string { return "ChanceValidationError" }

// Error satisfies the builtin error interface
func (e ChanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChanceValidationError{}

// Validate checks the field values on Media with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Media) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Media with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MediaMultiError, or nil if none found.
func (m *Media) ValidateAll() error {
	return m.validate(true)
}

func (m *Media) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MimeType

	// no validation rules for Url

	if len(errors) > 0 {
		return MediaMultiError(errors)
	}

	return nil
}

// MediaMultiError is an error wrapping multiple validation errors returned by
// Media.ValidateAll() if the designated constraints aren't met.
type MediaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MediaMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MediaMultiError) AllErrors() []error { return m }

// MediaValidationError is the validation error returned by Media.Validate if
// the designated constraints aren't met.
type MediaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MediaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MediaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MediaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MediaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MediaValidationError) ErrorName() string { return "MediaValidationError" }

// Error satisfies the builtin error interface
func (e MediaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMedia.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MediaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MediaValidationError{}

// Validate checks the field values on Commodity_Extra with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Commodity_Extra) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Commodity_Extra with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Commodity_ExtraMultiError, or nil if none found.
func (m *Commodity_Extra) ValidateAll() error {
	return m.validate(true)
}

func (m *Commodity_Extra) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Context

	if len(errors) > 0 {
		return Commodity_ExtraMultiError(errors)
	}

	return nil
}

// Commodity_ExtraMultiError is an error wrapping multiple validation errors
// returned by Commodity_Extra.ValidateAll() if the designated constraints
// aren't met.
type Commodity_ExtraMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Commodity_ExtraMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Commodity_ExtraMultiError) AllErrors() []error { return m }

// Commodity_ExtraValidationError is the validation error returned by
// Commodity_Extra.Validate if the designated constraints aren't met.
type Commodity_ExtraValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Commodity_ExtraValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Commodity_ExtraValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Commodity_ExtraValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Commodity_ExtraValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Commodity_ExtraValidationError) ErrorName() string { return "Commodity_ExtraValidationError" }

// Error satisfies the builtin error interface
func (e Commodity_ExtraValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommodity_Extra.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Commodity_ExtraValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Commodity_ExtraValidationError{}

// Validate checks the field values on Chance_SellingPoint with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Chance_SellingPoint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Chance_SellingPoint with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Chance_SellingPointMultiError, or nil if none found.
func (m *Chance_SellingPoint) ValidateAll() error {
	return m.validate(true)
}

func (m *Chance_SellingPoint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Description

	if len(errors) > 0 {
		return Chance_SellingPointMultiError(errors)
	}

	return nil
}

// Chance_SellingPointMultiError is an error wrapping multiple validation
// errors returned by Chance_SellingPoint.ValidateAll() if the designated
// constraints aren't met.
type Chance_SellingPointMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Chance_SellingPointMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Chance_SellingPointMultiError) AllErrors() []error { return m }

// Chance_SellingPointValidationError is the validation error returned by
// Chance_SellingPoint.Validate if the designated constraints aren't met.
type Chance_SellingPointValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Chance_SellingPointValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Chance_SellingPointValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Chance_SellingPointValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Chance_SellingPointValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Chance_SellingPointValidationError) ErrorName() string {
	return "Chance_SellingPointValidationError"
}

// Error satisfies the builtin error interface
func (e Chance_SellingPointValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChance_SellingPoint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Chance_SellingPointValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Chance_SellingPointValidationError{}

// Validate checks the field values on Chance_TargetAudience with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Chance_TargetAudience) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Chance_TargetAudience with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Chance_TargetAudienceMultiError, or nil if none found.
func (m *Chance_TargetAudience) ValidateAll() error {
	return m.validate(true)
}

func (m *Chance_TargetAudience) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Description

	if len(errors) > 0 {
		return Chance_TargetAudienceMultiError(errors)
	}

	return nil
}

// Chance_TargetAudienceMultiError is an error wrapping multiple validation
// errors returned by Chance_TargetAudience.ValidateAll() if the designated
// constraints aren't met.
type Chance_TargetAudienceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Chance_TargetAudienceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Chance_TargetAudienceMultiError) AllErrors() []error { return m }

// Chance_TargetAudienceValidationError is the validation error returned by
// Chance_TargetAudience.Validate if the designated constraints aren't met.
type Chance_TargetAudienceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Chance_TargetAudienceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Chance_TargetAudienceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Chance_TargetAudienceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Chance_TargetAudienceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Chance_TargetAudienceValidationError) ErrorName() string {
	return "Chance_TargetAudienceValidationError"
}

// Error satisfies the builtin error interface
func (e Chance_TargetAudienceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChance_TargetAudience.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Chance_TargetAudienceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Chance_TargetAudienceValidationError{}
