// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proj/session_service.proto

package projpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	_ "store/api/public/response"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_proj_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateSessionRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type UpdateSessionSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionSegmentRequest) Reset() {
	*x = UpdateSessionSegmentRequest{}
	mi := &file_proj_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSegmentRequest) ProtoMessage() {}

func (x *UpdateSessionSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSegmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionSegmentRequest) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSessionSegmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionSegmentRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateSessionSegmentRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proj_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proj_session_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommodityId   string                 `protobuf:"bytes,1,opt,name=commodityId,proto3" json:"commodityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proj_session_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetCommodityId() string {
	if x != nil {
		return x.CommodityId
	}
	return ""
}

type CreateSessionV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	CommodityId   string                 `protobuf:"bytes,2,opt,name=commodityId,proto3" json:"commodityId,omitempty"`
	TargetChance  int64                  `protobuf:"varint,3,opt,name=targetChance,proto3" json:"targetChance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionV2Request) Reset() {
	*x = CreateSessionV2Request{}
	mi := &file_proj_session_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionV2Request) ProtoMessage() {}

func (x *CreateSessionV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proj_session_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionV2Request.ProtoReflect.Descriptor instead.
func (*CreateSessionV2Request) Descriptor() ([]byte, []int) {
	return file_proj_session_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionV2Request) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateSessionV2Request) GetCommodityId() string {
	if x != nil {
		return x.CommodityId
	}
	return ""
}

func (x *CreateSessionV2Request) GetTargetChance() int64 {
	if x != nil {
		return x.TargetChance
	}
	return 0
}

var File_proj_session_service_proto protoreflect.FileDescriptor

const file_proj_session_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproj/session_service.proto\x12\bapi.proj\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1epublic/response/response.proto\x1a\x17validate/validate.proto\x1a\x0fproj/task.proto\x1a\x0fproj/user.proto\x1a\x11proj/credit.proto\x1a\x12proj/account.proto\x1a\x12proj/session.proto\"\xbd\x01\n" +
	"\x14UpdateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12B\n" +
	"\x06params\x18\x03 \x03(\v2*.api.proj.UpdateSessionRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x1bUpdateSessionSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12I\n" +
	"\x06params\x18\x03 \x03(\v21.api.proj.UpdateSessionSegmentRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x13ListSessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\"8\n" +
	"\x14CreateSessionRequest\x12 \n" +
	"\vcommodityId\x18\x01 \x01(\tR\vcommodityId\"~\n" +
	"\x16CreateSessionV2Request\x12\x1e\n" +
	"\n" +
	"templateId\x18\x01 \x01(\tR\n" +
	"templateId\x12 \n" +
	"\vcommodityId\x18\x02 \x01(\tR\vcommodityId\x12\"\n" +
	"\ftargetChance\x18\x03 \x01(\x03R\ftargetChance2\x99\x05\n" +
	"\x0eSessionService\x12d\n" +
	"\rCreateSession\x12\x1e.api.proj.CreateSessionRequest\x1a\x11.api.proj.Session\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/proj/v1/sessions\x12h\n" +
	"\x0fCreateSessionV2\x12 .api.proj.CreateSessionV2Request\x1a\x11.api.proj.Session\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/proj/v2/sessions\x12`\n" +
	"\n" +
	"GetSession\x12\x1b.api.proj.GetSessionRequest\x1a\x11.api.proj.Session\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/proj/v1/sessions/{id}\x12c\n" +
	"\fListSessions\x12\x1d.api.proj.ListSessionsRequest\x1a\x15.api.proj.SessionList\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/proj/v1/sessions\x12i\n" +
	"\rUpdateSession\x12\x1e.api.proj.UpdateSessionRequest\x1a\x11.api.proj.Session\"%\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/api/proj/v1/sessions/{id}\x12\x84\x01\n" +
	"\x14UpdateSessionSegment\x12%.api.proj.UpdateSessionSegmentRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*2\"/api/proj/v1/session-segments/{id}B\x17Z\x15store/api/proj;projpbb\x06proto3"

var (
	file_proj_session_service_proto_rawDescOnce sync.Once
	file_proj_session_service_proto_rawDescData []byte
)

func file_proj_session_service_proto_rawDescGZIP() []byte {
	file_proj_session_service_proto_rawDescOnce.Do(func() {
		file_proj_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proj_session_service_proto_rawDesc), len(file_proj_session_service_proto_rawDesc)))
	})
	return file_proj_session_service_proto_rawDescData
}

var file_proj_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proj_session_service_proto_goTypes = []any{
	(*UpdateSessionRequest)(nil),        // 0: api.proj.UpdateSessionRequest
	(*UpdateSessionSegmentRequest)(nil), // 1: api.proj.UpdateSessionSegmentRequest
	(*GetSessionRequest)(nil),           // 2: api.proj.GetSessionRequest
	(*ListSessionsRequest)(nil),         // 3: api.proj.ListSessionsRequest
	(*CreateSessionRequest)(nil),        // 4: api.proj.CreateSessionRequest
	(*CreateSessionV2Request)(nil),      // 5: api.proj.CreateSessionV2Request
	nil,                                 // 6: api.proj.UpdateSessionRequest.ParamsEntry
	nil,                                 // 7: api.proj.UpdateSessionSegmentRequest.ParamsEntry
	(*Session)(nil),                     // 8: api.proj.Session
	(*SessionList)(nil),                 // 9: api.proj.SessionList
	(*emptypb.Empty)(nil),               // 10: google.protobuf.Empty
}
var file_proj_session_service_proto_depIdxs = []int32{
	6,  // 0: api.proj.UpdateSessionRequest.params:type_name -> api.proj.UpdateSessionRequest.ParamsEntry
	7,  // 1: api.proj.UpdateSessionSegmentRequest.params:type_name -> api.proj.UpdateSessionSegmentRequest.ParamsEntry
	4,  // 2: api.proj.SessionService.CreateSession:input_type -> api.proj.CreateSessionRequest
	5,  // 3: api.proj.SessionService.CreateSessionV2:input_type -> api.proj.CreateSessionV2Request
	2,  // 4: api.proj.SessionService.GetSession:input_type -> api.proj.GetSessionRequest
	3,  // 5: api.proj.SessionService.ListSessions:input_type -> api.proj.ListSessionsRequest
	0,  // 6: api.proj.SessionService.UpdateSession:input_type -> api.proj.UpdateSessionRequest
	1,  // 7: api.proj.SessionService.UpdateSessionSegment:input_type -> api.proj.UpdateSessionSegmentRequest
	8,  // 8: api.proj.SessionService.CreateSession:output_type -> api.proj.Session
	8,  // 9: api.proj.SessionService.CreateSessionV2:output_type -> api.proj.Session
	8,  // 10: api.proj.SessionService.GetSession:output_type -> api.proj.Session
	9,  // 11: api.proj.SessionService.ListSessions:output_type -> api.proj.SessionList
	8,  // 12: api.proj.SessionService.UpdateSession:output_type -> api.proj.Session
	10, // 13: api.proj.SessionService.UpdateSessionSegment:output_type -> google.protobuf.Empty
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proj_session_service_proto_init() }
func file_proj_session_service_proto_init() {
	if File_proj_session_service_proto != nil {
		return
	}
	file_proj_task_proto_init()
	file_proj_user_proto_init()
	file_proj_credit_proto_init()
	file_proj_account_proto_init()
	file_proj_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proj_session_service_proto_rawDesc), len(file_proj_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proj_session_service_proto_goTypes,
		DependencyIndexes: file_proj_session_service_proto_depIdxs,
		MessageInfos:      file_proj_session_service_proto_msgTypes,
	}.Build()
	File_proj_session_service_proto = out.File
	file_proj_session_service_proto_goTypes = nil
	file_proj_session_service_proto_depIdxs = nil
}
