// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proj/workflow.proto

package projpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inspiration   string                 `protobuf:"bytes,4,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Images        []string               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Segments      []*ResourceSegment     `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentScript) Reset() {
	*x = SegmentScript{}
	mi := &file_proj_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentScript) ProtoMessage() {}

func (x *SegmentScript) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentScript.ProtoReflect.Descriptor instead.
func (*SegmentScript) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentScript) GetInspiration() string {
	if x != nil {
		return x.Inspiration
	}
	return ""
}

func (x *SegmentScript) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *SegmentScript) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SegmentScript) GetSegments() []*ResourceSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type VideoGeneration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	FirstFrame    string                 `protobuf:"bytes,5,opt,name=firstFrame,proto3" json:"firstFrame,omitempty"`
	LastFrame     string                 `protobuf:"bytes,6,opt,name=lastFrame,proto3" json:"lastFrame,omitempty"`
	Prompt        string                 `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty"`
	TmpPrompt     string                 `protobuf:"bytes,9,opt,name=tmpPrompt,proto3" json:"tmpPrompt,omitempty"`
	Subtitle      string                 `protobuf:"bytes,8,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	AspectRatio   string                 `protobuf:"bytes,10,opt,name=aspectRatio,proto3" json:"aspectRatio,omitempty"`
	Duration      int64                  `protobuf:"varint,11,opt,name=duration,proto3" json:"duration,omitempty"`
	Category      string                 `protobuf:"bytes,12,opt,name=category,proto3" json:"category,omitempty"`
	Error         string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGeneration) Reset() {
	*x = VideoGeneration{}
	mi := &file_proj_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGeneration) ProtoMessage() {}

func (x *VideoGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGeneration.ProtoReflect.Descriptor instead.
func (*VideoGeneration) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *VideoGeneration) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoGeneration) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *VideoGeneration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoGeneration) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoGeneration) GetFirstFrame() string {
	if x != nil {
		return x.FirstFrame
	}
	return ""
}

func (x *VideoGeneration) GetLastFrame() string {
	if x != nil {
		return x.LastFrame
	}
	return ""
}

func (x *VideoGeneration) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *VideoGeneration) GetTmpPrompt() string {
	if x != nil {
		return x.TmpPrompt
	}
	return ""
}

func (x *VideoGeneration) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *VideoGeneration) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *VideoGeneration) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoGeneration) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VideoGeneration) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VideoFramesChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstFrame    string                 `protobuf:"bytes,1,opt,name=firstFrame,proto3" json:"firstFrame,omitempty"`
	NewFirstFrame string                 `protobuf:"bytes,2,opt,name=newFirstFrame,proto3" json:"newFirstFrame,omitempty"`
	LastFrame     string                 `protobuf:"bytes,3,opt,name=lastFrame,proto3" json:"lastFrame,omitempty"`
	NewLastFrame  string                 `protobuf:"bytes,4,opt,name=newLastFrame,proto3" json:"newLastFrame,omitempty"`
	Ref           string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFramesChange) Reset() {
	*x = VideoFramesChange{}
	mi := &file_proj_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFramesChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFramesChange) ProtoMessage() {}

func (x *VideoFramesChange) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFramesChange.ProtoReflect.Descriptor instead.
func (*VideoFramesChange) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *VideoFramesChange) GetFirstFrame() string {
	if x != nil {
		return x.FirstFrame
	}
	return ""
}

func (x *VideoFramesChange) GetNewFirstFrame() string {
	if x != nil {
		return x.NewFirstFrame
	}
	return ""
}

func (x *VideoFramesChange) GetLastFrame() string {
	if x != nil {
		return x.LastFrame
	}
	return ""
}

func (x *VideoFramesChange) GetNewLastFrame() string {
	if x != nil {
		return x.NewLastFrame
	}
	return ""
}

func (x *VideoFramesChange) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type Remix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Segments      []*Remix_Segment       `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remix) Reset() {
	*x = Remix{}
	mi := &file_proj_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remix) ProtoMessage() {}

func (x *Remix) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remix.ProtoReflect.Descriptor instead.
func (*Remix) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *Remix) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Remix) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Remix) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Remix) GetSegments() []*Remix_Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Remix) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pass          bool                   `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proj_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *Review) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *Review) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type KeyFrames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*KeyFrames_Frame     `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyFrames) Reset() {
	*x = KeyFrames{}
	mi := &file_proj_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFrames) ProtoMessage() {}

func (x *KeyFrames) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFrames.ProtoReflect.Descriptor instead.
func (*KeyFrames) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *KeyFrames) GetFrames() []*KeyFrames_Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *KeyFrames) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DataBus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,20,opt,name=userId,proto3" json:"userId,omitempty"`
	Segment   *ResourceSegment       `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	Commodity *Commodity             `protobuf:"bytes,2,opt,name=commodity,proto3" json:"commodity,omitempty"`
	Settings  *DataBus_Settings      `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	// api.proj.ResourceSegment segment_CommodityReplacement = 3;
	VideoGenerations   []*VideoGeneration   `protobuf:"bytes,4,rep,name=videoGenerations,proto3" json:"videoGenerations,omitempty"`
	VideoFramesChanges []*VideoFramesChange `protobuf:"bytes,5,rep,name=videoFramesChanges,proto3" json:"videoFramesChanges,omitempty"`
	Remix              *Remix               `protobuf:"bytes,6,opt,name=remix,proto3" json:"remix,omitempty"`
	SegmentScript      *SegmentScript       `protobuf:"bytes,7,opt,name=segmentScript,proto3" json:"segmentScript,omitempty"`
	KeyFrames          *KeyFrames           `protobuf:"bytes,8,opt,name=keyFrames,proto3" json:"keyFrames,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataBus) Reset() {
	*x = DataBus{}
	mi := &file_proj_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBus) ProtoMessage() {}

func (x *DataBus) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBus.ProtoReflect.Descriptor instead.
func (*DataBus) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *DataBus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataBus) GetSegment() *ResourceSegment {
	if x != nil {
		return x.Segment
	}
	return nil
}

func (x *DataBus) GetCommodity() *Commodity {
	if x != nil {
		return x.Commodity
	}
	return nil
}

func (x *DataBus) GetSettings() *DataBus_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *DataBus) GetVideoGenerations() []*VideoGeneration {
	if x != nil {
		return x.VideoGenerations
	}
	return nil
}

func (x *DataBus) GetVideoFramesChanges() []*VideoFramesChange {
	if x != nil {
		return x.VideoFramesChanges
	}
	return nil
}

func (x *DataBus) GetRemix() *Remix {
	if x != nil {
		return x.Remix
	}
	return nil
}

func (x *DataBus) GetSegmentScript() *SegmentScript {
	if x != nil {
		return x.SegmentScript
	}
	return nil
}

func (x *DataBus) GetKeyFrames() *KeyFrames {
	if x != nil {
		return x.KeyFrames
	}
	return nil
}

type Job struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index       int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status      string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt   int64                  `protobuf:"varint,6,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	CompletedAt int64                  `protobuf:"varint,7,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	Progress    *Job_Progress          `protobuf:"bytes,8,opt,name=progress,proto3" json:"progress,omitempty"`
	// map<string, string> context = 20;
	DataBus       *DataBus `protobuf:"bytes,9,opt,name=dataBus,proto3" json:"dataBus,omitempty"`
	SubJobs       []*Job   `protobuf:"bytes,10,rep,name=subJobs,proto3" json:"subJobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proj_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Job) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Job) GetProgress() *Job_Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *Job) GetDataBus() *DataBus {
	if x != nil {
		return x.DataBus
	}
	return nil
}

func (x *Job) GetSubJobs() []*Job {
	if x != nil {
		return x.SubJobs
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,proto3" json:"_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Current       int64                  `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completedAt,proto3" json:"completedAt,omitempty"`
	LastResumedAt int64                  `protobuf:"varint,9,opt,name=lastResumedAt,proto3" json:"lastResumedAt,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	Auto          bool                   `protobuf:"varint,10,opt,name=auto,proto3" json:"auto,omitempty"`
	DataBus       *DataBus               `protobuf:"bytes,20,opt,name=dataBus,proto3" json:"dataBus,omitempty"`
	Data          *DataBus               `protobuf:"bytes,21,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_proj_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *Workflow) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Workflow) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Workflow) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Workflow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workflow) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Workflow) GetLastResumedAt() int64 {
	if x != nil {
		return x.LastResumedAt
	}
	return 0
}

func (x *Workflow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Workflow) GetAuto() bool {
	if x != nil {
		return x.Auto
	}
	return false
}

func (x *Workflow) GetDataBus() *DataBus {
	if x != nil {
		return x.DataBus
	}
	return nil
}

func (x *Workflow) GetData() *DataBus {
	if x != nil {
		return x.Data
	}
	return nil
}

type Remix_Segment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaId         string                 `protobuf:"bytes,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	VideoGeneration *VideoGeneration       `protobuf:"bytes,2,opt,name=videoGeneration,proto3" json:"videoGeneration,omitempty"`
	RemixOptions    *RemixOptions          `protobuf:"bytes,3,opt,name=remixOptions,proto3" json:"remixOptions,omitempty"`
	ScriptSegment   *ResourceSegment       `protobuf:"bytes,4,opt,name=scriptSegment,proto3" json:"scriptSegment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Remix_Segment) Reset() {
	*x = Remix_Segment{}
	mi := &file_proj_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remix_Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remix_Segment) ProtoMessage() {}

func (x *Remix_Segment) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remix_Segment.ProtoReflect.Descriptor instead.
func (*Remix_Segment) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Remix_Segment) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Remix_Segment) GetVideoGeneration() *VideoGeneration {
	if x != nil {
		return x.VideoGeneration
	}
	return nil
}

func (x *Remix_Segment) GetRemixOptions() *RemixOptions {
	if x != nil {
		return x.RemixOptions
	}
	return nil
}

func (x *Remix_Segment) GetScriptSegment() *ResourceSegment {
	if x != nil {
		return x.ScriptSegment
	}
	return nil
}

type KeyFrames_Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Refs          []string               `protobuf:"bytes,5,rep,name=refs,proto3" json:"refs,omitempty"`
	TaskId        string                 `protobuf:"bytes,6,opt,name=taskId,proto3" json:"taskId,omitempty"`
	AspectRatio   string                 `protobuf:"bytes,7,opt,name=aspectRatio,proto3" json:"aspectRatio,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Category      string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Review        *Review                `protobuf:"bytes,10,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyFrames_Frame) Reset() {
	*x = KeyFrames_Frame{}
	mi := &file_proj_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyFrames_Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFrames_Frame) ProtoMessage() {}

func (x *KeyFrames_Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFrames_Frame.ProtoReflect.Descriptor instead.
func (*KeyFrames_Frame) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{5, 0}
}

func (x *KeyFrames_Frame) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *KeyFrames_Frame) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *KeyFrames_Frame) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KeyFrames_Frame) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *KeyFrames_Frame) GetRefs() []string {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *KeyFrames_Frame) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *KeyFrames_Frame) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *KeyFrames_Frame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *KeyFrames_Frame) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *KeyFrames_Frame) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DataBus_Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AspectRatio   string                 `protobuf:"bytes,1,opt,name=aspectRatio,proto3" json:"aspectRatio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBus_Settings) Reset() {
	*x = DataBus_Settings{}
	mi := &file_proj_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBus_Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBus_Settings) ProtoMessage() {}

func (x *DataBus_Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBus_Settings.ProtoReflect.Descriptor instead.
func (*DataBus_Settings) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DataBus_Settings) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

type Job_Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Current       int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job_Progress) Reset() {
	*x = Job_Progress{}
	mi := &file_proj_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job_Progress) ProtoMessage() {}

func (x *Job_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_proj_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job_Progress.ProtoReflect.Descriptor instead.
func (*Job_Progress) Descriptor() ([]byte, []int) {
	return file_proj_workflow_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Job_Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Job_Progress) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

var File_proj_workflow_proto protoreflect.FileDescriptor

const file_proj_workflow_proto_rawDesc = "" +
	"\n" +
	"\x13proj/workflow.proto\x12\bapi.proj\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fproj/item.proto\x1a\x14proj/commodity.proto\x1a\x17proj/remixoptions.proto\"\x98\x01\n" +
	"\rSegmentScript\x12 \n" +
	"\vinspiration\x18\x04 \x01(\tR\vinspiration\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x16\n" +
	"\x06images\x18\x02 \x03(\tR\x06images\x125\n" +
	"\bsegments\x18\x03 \x03(\v2\x19.api.proj.ResourceSegmentR\bsegments\"\xef\x02\n" +
	"\x0fVideoGeneration\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x1e\n" +
	"\n" +
	"firstFrame\x18\x05 \x01(\tR\n" +
	"firstFrame\x12\x1c\n" +
	"\tlastFrame\x18\x06 \x01(\tR\tlastFrame\x12\x16\n" +
	"\x06prompt\x18\a \x01(\tR\x06prompt\x12\x1c\n" +
	"\ttmpPrompt\x18\t \x01(\tR\ttmpPrompt\x12\x1a\n" +
	"\bsubtitle\x18\b \x01(\tR\bsubtitle\x12 \n" +
	"\vaspectRatio\x18\n" +
	" \x01(\tR\vaspectRatio\x12\x1a\n" +
	"\bduration\x18\v \x01(\x03R\bduration\x12\x1a\n" +
	"\bcategory\x18\f \x01(\tR\bcategory\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"\xad\x01\n" +
	"\x11VideoFramesChange\x12\x1e\n" +
	"\n" +
	"firstFrame\x18\x01 \x01(\tR\n" +
	"firstFrame\x12$\n" +
	"\rnewFirstFrame\x18\x02 \x01(\tR\rnewFirstFrame\x12\x1c\n" +
	"\tlastFrame\x18\x03 \x01(\tR\tlastFrame\x12\"\n" +
	"\fnewLastFrame\x18\x04 \x01(\tR\fnewLastFrame\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\"\x82\x03\n" +
	"\x05Remix\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bcoverUrl\x18\x04 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\tR\x06taskId\x123\n" +
	"\bsegments\x18\x03 \x03(\v2\x17.api.proj.Remix.SegmentR\bsegments\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x1a\xe5\x01\n" +
	"\aSegment\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\tR\amediaId\x12C\n" +
	"\x0fvideoGeneration\x18\x02 \x01(\v2\x19.api.proj.VideoGenerationR\x0fvideoGeneration\x12:\n" +
	"\fremixOptions\x18\x03 \x01(\v2\x16.api.proj.RemixOptionsR\fremixOptions\x12?\n" +
	"\rscriptSegment\x18\x04 \x01(\v2\x19.api.proj.ResourceSegmentR\rscriptSegment\"0\n" +
	"\x06Review\x12\x12\n" +
	"\x04pass\x18\x01 \x01(\bR\x04pass\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\xe0\x02\n" +
	"\tKeyFrames\x121\n" +
	"\x06frames\x18\x01 \x03(\v2\x19.api.proj.KeyFrames.FrameR\x06frames\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\tR\x06taskId\x1a\x87\x02\n" +
	"\x05Frame\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04refs\x18\x05 \x03(\tR\x04refs\x12\x16\n" +
	"\x06taskId\x18\x06 \x01(\tR\x06taskId\x12 \n" +
	"\vaspectRatio\x18\a \x01(\tR\vaspectRatio\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12(\n" +
	"\x06review\x18\n" +
	" \x01(\v2\x10.api.proj.ReviewR\x06review\"\x9c\x04\n" +
	"\aDataBus\x12\x16\n" +
	"\x06userId\x18\x14 \x01(\tR\x06userId\x123\n" +
	"\asegment\x18\x01 \x01(\v2\x19.api.proj.ResourceSegmentR\asegment\x121\n" +
	"\tcommodity\x18\x02 \x01(\v2\x13.api.proj.CommodityR\tcommodity\x126\n" +
	"\bsettings\x18\x03 \x01(\v2\x1a.api.proj.DataBus.SettingsR\bsettings\x12E\n" +
	"\x10videoGenerations\x18\x04 \x03(\v2\x19.api.proj.VideoGenerationR\x10videoGenerations\x12K\n" +
	"\x12videoFramesChanges\x18\x05 \x03(\v2\x1b.api.proj.VideoFramesChangeR\x12videoFramesChanges\x12%\n" +
	"\x05remix\x18\x06 \x01(\v2\x0f.api.proj.RemixR\x05remix\x12=\n" +
	"\rsegmentScript\x18\a \x01(\v2\x17.api.proj.SegmentScriptR\rsegmentScript\x121\n" +
	"\tkeyFrames\x18\b \x01(\v2\x13.api.proj.KeyFramesR\tkeyFrames\x1a,\n" +
	"\bSettings\x12 \n" +
	"\vaspectRatio\x18\x01 \x01(\tR\vaspectRatio\"\xcd\x02\n" +
	"\x03Job\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartedAt\x18\x06 \x01(\x03R\tstartedAt\x12 \n" +
	"\vcompletedAt\x18\a \x01(\x03R\vcompletedAt\x122\n" +
	"\bprogress\x18\b \x01(\v2\x16.api.proj.Job.ProgressR\bprogress\x12+\n" +
	"\adataBus\x18\t \x01(\v2\x11.api.proj.DataBusR\adataBus\x12'\n" +
	"\asubJobs\x18\n" +
	" \x03(\v2\r.api.proj.JobR\asubJobs\x1a:\n" +
	"\bProgress\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\"\xeb\x02\n" +
	"\bWorkflow\x12\x10\n" +
	"\x03_id\x18\x01 \x01(\tR\x03_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acurrent\x18\x05 \x01(\x03R\acurrent\x12!\n" +
	"\x04jobs\x18\x03 \x03(\v2\r.api.proj.JobR\x04jobs\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vcompletedAt\x18\a \x01(\x03R\vcompletedAt\x12$\n" +
	"\rlastResumedAt\x18\t \x01(\x03R\rlastResumedAt\x12\x16\n" +
	"\x06userId\x18\b \x01(\tR\x06userId\x12\x12\n" +
	"\x04auto\x18\n" +
	" \x01(\bR\x04auto\x12+\n" +
	"\adataBus\x18\x14 \x01(\v2\x11.api.proj.DataBusR\adataBus\x12%\n" +
	"\x04data\x18\x15 \x01(\v2\x11.api.proj.DataBusR\x04dataB\x17Z\x15store/api/proj;projpbb\x06proto3"

var (
	file_proj_workflow_proto_rawDescOnce sync.Once
	file_proj_workflow_proto_rawDescData []byte
)

func file_proj_workflow_proto_rawDescGZIP() []byte {
	file_proj_workflow_proto_rawDescOnce.Do(func() {
		file_proj_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proj_workflow_proto_rawDesc), len(file_proj_workflow_proto_rawDesc)))
	})
	return file_proj_workflow_proto_rawDescData
}

var file_proj_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proj_workflow_proto_goTypes = []any{
	(*SegmentScript)(nil),     // 0: api.proj.SegmentScript
	(*VideoGeneration)(nil),   // 1: api.proj.VideoGeneration
	(*VideoFramesChange)(nil), // 2: api.proj.VideoFramesChange
	(*Remix)(nil),             // 3: api.proj.Remix
	(*Review)(nil),            // 4: api.proj.Review
	(*KeyFrames)(nil),         // 5: api.proj.KeyFrames
	(*DataBus)(nil),           // 6: api.proj.DataBus
	(*Job)(nil),               // 7: api.proj.Job
	(*Workflow)(nil),          // 8: api.proj.Workflow
	(*Remix_Segment)(nil),     // 9: api.proj.Remix.Segment
	(*KeyFrames_Frame)(nil),   // 10: api.proj.KeyFrames.Frame
	(*DataBus_Settings)(nil),  // 11: api.proj.DataBus.Settings
	(*Job_Progress)(nil),      // 12: api.proj.Job.Progress
	(*ResourceSegment)(nil),   // 13: api.proj.ResourceSegment
	(*Commodity)(nil),         // 14: api.proj.Commodity
	(*RemixOptions)(nil),      // 15: api.proj.RemixOptions
}
var file_proj_workflow_proto_depIdxs = []int32{
	13, // 0: api.proj.SegmentScript.segments:type_name -> api.proj.ResourceSegment
	9,  // 1: api.proj.Remix.segments:type_name -> api.proj.Remix.Segment
	10, // 2: api.proj.KeyFrames.frames:type_name -> api.proj.KeyFrames.Frame
	13, // 3: api.proj.DataBus.segment:type_name -> api.proj.ResourceSegment
	14, // 4: api.proj.DataBus.commodity:type_name -> api.proj.Commodity
	11, // 5: api.proj.DataBus.settings:type_name -> api.proj.DataBus.Settings
	1,  // 6: api.proj.DataBus.videoGenerations:type_name -> api.proj.VideoGeneration
	2,  // 7: api.proj.DataBus.videoFramesChanges:type_name -> api.proj.VideoFramesChange
	3,  // 8: api.proj.DataBus.remix:type_name -> api.proj.Remix
	0,  // 9: api.proj.DataBus.segmentScript:type_name -> api.proj.SegmentScript
	5,  // 10: api.proj.DataBus.keyFrames:type_name -> api.proj.KeyFrames
	12, // 11: api.proj.Job.progress:type_name -> api.proj.Job.Progress
	6,  // 12: api.proj.Job.dataBus:type_name -> api.proj.DataBus
	7,  // 13: api.proj.Job.subJobs:type_name -> api.proj.Job
	7,  // 14: api.proj.Workflow.jobs:type_name -> api.proj.Job
	6,  // 15: api.proj.Workflow.dataBus:type_name -> api.proj.DataBus
	6,  // 16: api.proj.Workflow.data:type_name -> api.proj.DataBus
	1,  // 17: api.proj.Remix.Segment.videoGeneration:type_name -> api.proj.VideoGeneration
	15, // 18: api.proj.Remix.Segment.remixOptions:type_name -> api.proj.RemixOptions
	13, // 19: api.proj.Remix.Segment.scriptSegment:type_name -> api.proj.ResourceSegment
	4,  // 20: api.proj.KeyFrames.Frame.review:type_name -> api.proj.Review
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proj_workflow_proto_init() }
func file_proj_workflow_proto_init() {
	if File_proj_workflow_proto != nil {
		return
	}
	file_proj_item_proto_init()
	file_proj_commodity_proto_init()
	file_proj_remixoptions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proj_workflow_proto_rawDesc), len(file_proj_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proj_workflow_proto_goTypes,
		DependencyIndexes: file_proj_workflow_proto_depIdxs,
		MessageInfos:      file_proj_workflow_proto_msgTypes,
	}.Build()
	File_proj_workflow_proto = out.File
	file_proj_workflow_proto_goTypes = nil
	file_proj_workflow_proto_depIdxs = nil
}
