// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dexx/trade_service.proto

package dexxpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListFollowingTradesParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListFollowingTradesParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListFollowingTradesParams with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListFollowingTradesParamsMultiError, or nil if none found.
func (m *ListFollowingTradesParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListFollowingTradesParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Category

	if all {
		switch v := interface{}(m.GetAuthorization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListFollowingTradesParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListFollowingTradesParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthorization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListFollowingTradesParamsValidationError{
				field:  "Authorization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListFollowingTradesParamsMultiError(errors)
	}

	return nil
}

// ListFollowingTradesParamsMultiError is an error wrapping multiple validation
// errors returned by ListFollowingTradesParams.ValidateAll() if the
// designated constraints aren't met.
type ListFollowingTradesParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListFollowingTradesParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListFollowingTradesParamsMultiError) AllErrors() []error { return m }

// ListFollowingTradesParamsValidationError is the validation error returned by
// ListFollowingTradesParams.Validate if the designated constraints aren't met.
type ListFollowingTradesParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListFollowingTradesParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListFollowingTradesParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListFollowingTradesParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListFollowingTradesParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListFollowingTradesParamsValidationError) ErrorName() string {
	return "ListFollowingTradesParamsValidationError"
}

// Error satisfies the builtin error interface
func (e ListFollowingTradesParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListFollowingTradesParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListFollowingTradesParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListFollowingTradesParamsValidationError{}

// Validate checks the field values on ListTokenTradesParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTokenTradesParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTokenTradesParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTokenTradesParamsMultiError, or nil if none found.
func (m *ListTokenTradesParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTokenTradesParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return ListTokenTradesParamsMultiError(errors)
	}

	return nil
}

// ListTokenTradesParamsMultiError is an error wrapping multiple validation
// errors returned by ListTokenTradesParams.ValidateAll() if the designated
// constraints aren't met.
type ListTokenTradesParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTokenTradesParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTokenTradesParamsMultiError) AllErrors() []error { return m }

// ListTokenTradesParamsValidationError is the validation error returned by
// ListTokenTradesParams.Validate if the designated constraints aren't met.
type ListTokenTradesParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTokenTradesParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTokenTradesParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTokenTradesParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTokenTradesParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTokenTradesParamsValidationError) ErrorName() string {
	return "ListTokenTradesParamsValidationError"
}

// Error satisfies the builtin error interface
func (e ListTokenTradesParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTokenTradesParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTokenTradesParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTokenTradesParamsValidationError{}

// Validate checks the field values on ListWalletTradesParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListWalletTradesParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWalletTradesParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWalletTradesParamsMultiError, or nil if none found.
func (m *ListWalletTradesParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWalletTradesParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Wallet

	if len(errors) > 0 {
		return ListWalletTradesParamsMultiError(errors)
	}

	return nil
}

// ListWalletTradesParamsMultiError is an error wrapping multiple validation
// errors returned by ListWalletTradesParams.ValidateAll() if the designated
// constraints aren't met.
type ListWalletTradesParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWalletTradesParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWalletTradesParamsMultiError) AllErrors() []error { return m }

// ListWalletTradesParamsValidationError is the validation error returned by
// ListWalletTradesParams.Validate if the designated constraints aren't met.
type ListWalletTradesParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWalletTradesParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWalletTradesParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWalletTradesParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWalletTradesParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWalletTradesParamsValidationError) ErrorName() string {
	return "ListWalletTradesParamsValidationError"
}

// Error satisfies the builtin error interface
func (e ListWalletTradesParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWalletTradesParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWalletTradesParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWalletTradesParamsValidationError{}

// Validate checks the field values on TradeParams with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TradeParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TradeParams with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TradeParamsMultiError, or
// nil if none found.
func (m *TradeParams) ValidateAll() error {
	return m.validate(true)
}

func (m *TradeParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for Amount

	// no validation rules for Side

	// no validation rules for Category

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TradeParamsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TradeParamsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TradeParamsValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UniqueKey

	// no validation rules for Trigger

	// no validation rules for Wallet

	// no validation rules for PrivateKey

	if all {
		switch v := interface{}(m.GetFee()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TradeParamsValidationError{
					field:  "Fee",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TradeParamsValidationError{
					field:  "Fee",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFee()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TradeParamsValidationError{
				field:  "Fee",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TradeParamsMultiError(errors)
	}

	return nil
}

// TradeParamsMultiError is an error wrapping multiple validation errors
// returned by TradeParams.ValidateAll() if the designated constraints aren't met.
type TradeParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TradeParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TradeParamsMultiError) AllErrors() []error { return m }

// TradeParamsValidationError is the validation error returned by
// TradeParams.Validate if the designated constraints aren't met.
type TradeParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TradeParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TradeParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TradeParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TradeParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TradeParamsValidationError) ErrorName() string { return "TradeParamsValidationError" }

// Error satisfies the builtin error interface
func (e TradeParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTradeParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TradeParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TradeParamsValidationError{}

// Validate checks the field values on Fee with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Fee) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Fee with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FeeMultiError, or nil if none found.
func (m *Fee) ValidateAll() error {
	return m.validate(true)
}

func (m *Fee) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rate

	// no validation rules for Receiver

	if len(errors) > 0 {
		return FeeMultiError(errors)
	}

	return nil
}

// FeeMultiError is an error wrapping multiple validation errors returned by
// Fee.ValidateAll() if the designated constraints aren't met.
type FeeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FeeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FeeMultiError) AllErrors() []error { return m }

// FeeValidationError is the validation error returned by Fee.Validate if the
// designated constraints aren't met.
type FeeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FeeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FeeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FeeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FeeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FeeValidationError) ErrorName() string { return "FeeValidationError" }

// Error satisfies the builtin error interface
func (e FeeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFee.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FeeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FeeValidationError{}

// Validate checks the field values on RunTradeTaskParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunTradeTaskParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunTradeTaskParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunTradeTaskParamsMultiError, or nil if none found.
func (m *RunTradeTaskParams) ValidateAll() error {
	return m.validate(true)
}

func (m *RunTradeTaskParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Task

	// no validation rules for Params

	if len(errors) > 0 {
		return RunTradeTaskParamsMultiError(errors)
	}

	return nil
}

// RunTradeTaskParamsMultiError is an error wrapping multiple validation errors
// returned by RunTradeTaskParams.ValidateAll() if the designated constraints
// aren't met.
type RunTradeTaskParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunTradeTaskParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunTradeTaskParamsMultiError) AllErrors() []error { return m }

// RunTradeTaskParamsValidationError is the validation error returned by
// RunTradeTaskParams.Validate if the designated constraints aren't met.
type RunTradeTaskParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunTradeTaskParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunTradeTaskParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunTradeTaskParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunTradeTaskParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunTradeTaskParamsValidationError) ErrorName() string {
	return "RunTradeTaskParamsValidationError"
}

// Error satisfies the builtin error interface
func (e RunTradeTaskParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunTradeTaskParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunTradeTaskParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunTradeTaskParamsValidationError{}

// Validate checks the field values on GetTradeSettingsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTradeSettingsParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTradeSettingsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTradeSettingsParamsMultiError, or nil if none found.
func (m *GetTradeSettingsParams) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTradeSettingsParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAuthorization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTradeSettingsParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTradeSettingsParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthorization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTradeSettingsParamsValidationError{
				field:  "Authorization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTradeSettingsParamsMultiError(errors)
	}

	return nil
}

// GetTradeSettingsParamsMultiError is an error wrapping multiple validation
// errors returned by GetTradeSettingsParams.ValidateAll() if the designated
// constraints aren't met.
type GetTradeSettingsParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTradeSettingsParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTradeSettingsParamsMultiError) AllErrors() []error { return m }

// GetTradeSettingsParamsValidationError is the validation error returned by
// GetTradeSettingsParams.Validate if the designated constraints aren't met.
type GetTradeSettingsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTradeSettingsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTradeSettingsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTradeSettingsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTradeSettingsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTradeSettingsParamsValidationError) ErrorName() string {
	return "GetTradeSettingsParamsValidationError"
}

// Error satisfies the builtin error interface
func (e GetTradeSettingsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTradeSettingsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTradeSettingsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTradeSettingsParamsValidationError{}

// Validate checks the field values on UpdateTradeSettingsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTradeSettingsParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTradeSettingsParams with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTradeSettingsParamsMultiError, or nil if none found.
func (m *UpdateTradeSettingsParams) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTradeSettingsParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSettings()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTradeSettingsParamsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTradeSettingsParamsValidationError{
					field:  "Settings",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTradeSettingsParamsValidationError{
				field:  "Settings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAuthorization()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTradeSettingsParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTradeSettingsParamsValidationError{
					field:  "Authorization",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthorization()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTradeSettingsParamsValidationError{
				field:  "Authorization",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateTradeSettingsParamsMultiError(errors)
	}

	return nil
}

// UpdateTradeSettingsParamsMultiError is an error wrapping multiple validation
// errors returned by UpdateTradeSettingsParams.ValidateAll() if the
// designated constraints aren't met.
type UpdateTradeSettingsParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTradeSettingsParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTradeSettingsParamsMultiError) AllErrors() []error { return m }

// UpdateTradeSettingsParamsValidationError is the validation error returned by
// UpdateTradeSettingsParams.Validate if the designated constraints aren't met.
type UpdateTradeSettingsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTradeSettingsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTradeSettingsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTradeSettingsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTradeSettingsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTradeSettingsParamsValidationError) ErrorName() string {
	return "UpdateTradeSettingsParamsValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTradeSettingsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTradeSettingsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTradeSettingsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTradeSettingsParamsValidationError{}
