// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"store/app/user/internal/data/repo/ent/usercreditcost"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserCreditCost is the model entity for the UserCreditCost schema.
type UserCreditCost struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount       int64 `json:"amount,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCreditCost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercreditcost.FieldID, usercreditcost.FieldAmount:
			values[i] = new(sql.NullInt64)
		case usercreditcost.FieldUserID:
			values[i] = new(sql.NullString)
		case usercreditcost.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCreditCost fields.
func (ucc *UserCreditCost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercreditcost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ucc.ID = int64(value.Int64)
		case usercreditcost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ucc.CreatedAt = value.Time
			}
		case usercreditcost.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ucc.UserID = value.String
			}
		case usercreditcost.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				ucc.Amount = value.Int64
			}
		default:
			ucc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCreditCost.
// This includes values selected through modifiers, order, etc.
func (ucc *UserCreditCost) Value(name string) (ent.Value, error) {
	return ucc.selectValues.Get(name)
}

// Update returns a builder for updating this UserCreditCost.
// Note that you need to call UserCreditCost.Unwrap() before calling this method if this UserCreditCost
// was returned from a transaction, and the transaction was committed or rolled back.
func (ucc *UserCreditCost) Update() *UserCreditCostUpdateOne {
	return NewUserCreditCostClient(ucc.config).UpdateOne(ucc)
}

// Unwrap unwraps the UserCreditCost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ucc *UserCreditCost) Unwrap() *UserCreditCost {
	_tx, ok := ucc.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCreditCost is not a transactional entity")
	}
	ucc.config.driver = _tx.drv
	return ucc
}

// String implements the fmt.Stringer.
func (ucc *UserCreditCost) String() string {
	var builder strings.Builder
	builder.WriteString("UserCreditCost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ucc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ucc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(ucc.UserID)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", ucc.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// UserCreditCosts is a parsable slice of UserCreditCost.
type UserCreditCosts []*UserCreditCost
