// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"store/app/user/internal/data/repo/ent/usercreditcost"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreditCostCreate is the builder for creating a UserCreditCost entity.
type UserCreditCostCreate struct {
	config
	mutation *UserCreditCostMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (uccc *UserCreditCostCreate) SetCreatedAt(t time.Time) *UserCreditCostCreate {
	uccc.mutation.SetCreatedAt(t)
	return uccc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uccc *UserCreditCostCreate) SetNillableCreatedAt(t *time.Time) *UserCreditCostCreate {
	if t != nil {
		uccc.SetCreatedAt(*t)
	}
	return uccc
}

// SetUserID sets the "user_id" field.
func (uccc *UserCreditCostCreate) SetUserID(s string) *UserCreditCostCreate {
	uccc.mutation.SetUserID(s)
	return uccc
}

// SetAmount sets the "amount" field.
func (uccc *UserCreditCostCreate) SetAmount(i int64) *UserCreditCostCreate {
	uccc.mutation.SetAmount(i)
	return uccc
}

// SetID sets the "id" field.
func (uccc *UserCreditCostCreate) SetID(i int64) *UserCreditCostCreate {
	uccc.mutation.SetID(i)
	return uccc
}

// Mutation returns the UserCreditCostMutation object of the builder.
func (uccc *UserCreditCostCreate) Mutation() *UserCreditCostMutation {
	return uccc.mutation
}

// Save creates the UserCreditCost in the database.
func (uccc *UserCreditCostCreate) Save(ctx context.Context) (*UserCreditCost, error) {
	uccc.defaults()
	return withHooks(ctx, uccc.sqlSave, uccc.mutation, uccc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uccc *UserCreditCostCreate) SaveX(ctx context.Context) *UserCreditCost {
	v, err := uccc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uccc *UserCreditCostCreate) Exec(ctx context.Context) error {
	_, err := uccc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uccc *UserCreditCostCreate) ExecX(ctx context.Context) {
	if err := uccc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uccc *UserCreditCostCreate) defaults() {
	if _, ok := uccc.mutation.CreatedAt(); !ok {
		v := usercreditcost.DefaultCreatedAt()
		uccc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uccc *UserCreditCostCreate) check() error {
	if _, ok := uccc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserCreditCost.created_at"`)}
	}
	if _, ok := uccc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserCreditCost.user_id"`)}
	}
	if _, ok := uccc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserCreditCost.amount"`)}
	}
	return nil
}

func (uccc *UserCreditCostCreate) sqlSave(ctx context.Context) (*UserCreditCost, error) {
	if err := uccc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uccc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uccc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	uccc.mutation.id = &_node.ID
	uccc.mutation.done = true
	return _node, nil
}

func (uccc *UserCreditCostCreate) createSpec() (*UserCreditCost, *sqlgraph.CreateSpec) {
	var (
		_node = &UserCreditCost{config: uccc.config}
		_spec = sqlgraph.NewCreateSpec(usercreditcost.Table, sqlgraph.NewFieldSpec(usercreditcost.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = uccc.conflict
	if id, ok := uccc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uccc.mutation.CreatedAt(); ok {
		_spec.SetField(usercreditcost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uccc.mutation.UserID(); ok {
		_spec.SetField(usercreditcost.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := uccc.mutation.Amount(); ok {
		_spec.SetField(usercreditcost.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCreditCost.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCreditCostUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (uccc *UserCreditCostCreate) OnConflict(opts ...sql.ConflictOption) *UserCreditCostUpsertOne {
	uccc.conflict = opts
	return &UserCreditCostUpsertOne{
		create: uccc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uccc *UserCreditCostCreate) OnConflictColumns(columns ...string) *UserCreditCostUpsertOne {
	uccc.conflict = append(uccc.conflict, sql.ConflictColumns(columns...))
	return &UserCreditCostUpsertOne{
		create: uccc,
	}
}

type (
	// UserCreditCostUpsertOne is the builder for "upsert"-ing
	//  one UserCreditCost node.
	UserCreditCostUpsertOne struct {
		create *UserCreditCostCreate
	}

	// UserCreditCostUpsert is the "OnConflict" setter.
	UserCreditCostUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserCreditCostUpsert) SetUserID(v string) *UserCreditCostUpsert {
	u.Set(usercreditcost.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditCostUpsert) UpdateUserID() *UserCreditCostUpsert {
	u.SetExcluded(usercreditcost.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserCreditCostUpsert) SetAmount(v int64) *UserCreditCostUpsert {
	u.Set(usercreditcost.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserCreditCostUpsert) UpdateAmount() *UserCreditCostUpsert {
	u.SetExcluded(usercreditcost.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserCreditCostUpsert) AddAmount(v int64) *UserCreditCostUpsert {
	u.Add(usercreditcost.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usercreditcost.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserCreditCostUpsertOne) UpdateNewValues() *UserCreditCostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(usercreditcost.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usercreditcost.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserCreditCostUpsertOne) Ignore() *UserCreditCostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCreditCostUpsertOne) DoNothing() *UserCreditCostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreditCostCreate.OnConflict
// documentation for more info.
func (u *UserCreditCostUpsertOne) Update(set func(*UserCreditCostUpsert)) *UserCreditCostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCreditCostUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserCreditCostUpsertOne) SetUserID(v string) *UserCreditCostUpsertOne {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditCostUpsertOne) UpdateUserID() *UserCreditCostUpsertOne {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *UserCreditCostUpsertOne) SetAmount(v int64) *UserCreditCostUpsertOne {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserCreditCostUpsertOne) AddAmount(v int64) *UserCreditCostUpsertOne {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserCreditCostUpsertOne) UpdateAmount() *UserCreditCostUpsertOne {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *UserCreditCostUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreditCostCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCreditCostUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserCreditCostUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserCreditCostUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreditCostCreateBulk is the builder for creating many UserCreditCost entities in bulk.
type UserCreditCostCreateBulk struct {
	config
	builders []*UserCreditCostCreate
	conflict []sql.ConflictOption
}

// Save creates the UserCreditCost entities in the database.
func (ucccb *UserCreditCostCreateBulk) Save(ctx context.Context) ([]*UserCreditCost, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ucccb.builders))
	nodes := make([]*UserCreditCost, len(ucccb.builders))
	mutators := make([]Mutator, len(ucccb.builders))
	for i := range ucccb.builders {
		func(i int, root context.Context) {
			builder := ucccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserCreditCostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ucccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucccb *UserCreditCostCreateBulk) SaveX(ctx context.Context) []*UserCreditCost {
	v, err := ucccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucccb *UserCreditCostCreateBulk) Exec(ctx context.Context) error {
	_, err := ucccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucccb *UserCreditCostCreateBulk) ExecX(ctx context.Context) {
	if err := ucccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCreditCost.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCreditCostUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ucccb *UserCreditCostCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserCreditCostUpsertBulk {
	ucccb.conflict = opts
	return &UserCreditCostUpsertBulk{
		create: ucccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ucccb *UserCreditCostCreateBulk) OnConflictColumns(columns ...string) *UserCreditCostUpsertBulk {
	ucccb.conflict = append(ucccb.conflict, sql.ConflictColumns(columns...))
	return &UserCreditCostUpsertBulk{
		create: ucccb,
	}
}

// UserCreditCostUpsertBulk is the builder for "upsert"-ing
// a bulk of UserCreditCost nodes.
type UserCreditCostUpsertBulk struct {
	create *UserCreditCostCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usercreditcost.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserCreditCostUpsertBulk) UpdateNewValues() *UserCreditCostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(usercreditcost.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usercreditcost.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCreditCost.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserCreditCostUpsertBulk) Ignore() *UserCreditCostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCreditCostUpsertBulk) DoNothing() *UserCreditCostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreditCostCreateBulk.OnConflict
// documentation for more info.
func (u *UserCreditCostUpsertBulk) Update(set func(*UserCreditCostUpsert)) *UserCreditCostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCreditCostUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserCreditCostUpsertBulk) SetUserID(v string) *UserCreditCostUpsertBulk {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditCostUpsertBulk) UpdateUserID() *UserCreditCostUpsertBulk {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *UserCreditCostUpsertBulk) SetAmount(v int64) *UserCreditCostUpsertBulk {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserCreditCostUpsertBulk) AddAmount(v int64) *UserCreditCostUpsertBulk {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserCreditCostUpsertBulk) UpdateAmount() *UserCreditCostUpsertBulk {
	return u.Update(func(s *UserCreditCostUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *UserCreditCostUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreditCostCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreditCostCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCreditCostUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
