// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CreditConsumesColumns holds the columns for the "credit_consumes" table.
	CreditConsumesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp", "postgres": "timestamp"}},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "recharge_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
	}
	// CreditConsumesTable holds the schema information for the "credit_consumes" table.
	CreditConsumesTable = &schema.Table{
		Name:       "credit_consumes",
		Columns:    CreditConsumesColumns,
		PrimaryKey: []*schema.Column{CreditConsumesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "creditconsume_user_id",
				Unique:  false,
				Columns: []*schema.Column{CreditConsumesColumns[4]},
			},
		},
	}
	// CreditRechargesColumns holds the columns for the "credit_recharges" table.
	CreditRechargesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp", "postgres": "timestamp"}},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "plan_id", Type: field.TypeString},
		{Name: "quota", Type: field.TypeInt64},
		{Name: "cost", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "platform", Type: field.TypeString, Nullable: true},
		{Name: "expire_at", Type: field.TypeTime, Nullable: true},
	}
	// CreditRechargesTable holds the schema information for the "credit_recharges" table.
	CreditRechargesTable = &schema.Table{
		Name:       "credit_recharges",
		Columns:    CreditRechargesColumns,
		PrimaryKey: []*schema.Column{CreditRechargesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "creditrecharge_user_id_expire_at",
				Unique:  false,
				Columns: []*schema.Column{CreditRechargesColumns[3], CreditRechargesColumns[9]},
			},
		},
	}
	// UserPaymentsColumns holds the columns for the "user_payments" table.
	UserPaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "session_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "sub_id", Type: field.TypeString, Nullable: true},
		{Name: "platform", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "plan_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "expire_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"created", "expired", "complete", "failed", "cancelled"}, Default: "created"},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp", "postgres": "timestamp"}},
		{Name: "extra", Type: field.TypeJSON},
	}
	// UserPaymentsTable holds the schema information for the "user_payments" table.
	UserPaymentsTable = &schema.Table{
		Name:       "user_payments",
		Columns:    UserPaymentsColumns,
		PrimaryKey: []*schema.Column{UserPaymentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "payment_platform_sub_id",
				Unique:  false,
				Columns: []*schema.Column{UserPaymentsColumns[3], UserPaymentsColumns[2]},
			},
			{
				Name:    "payment_user_id_expire_at",
				Unique:  false,
				Columns: []*schema.Column{UserPaymentsColumns[4], UserPaymentsColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CreditConsumesTable,
		CreditRechargesTable,
		UserPaymentsTable,
	}
)

func init() {
	CreditConsumesTable.Annotation = &entsql.Annotation{
		Table: "credit_consumes",
	}
	CreditRechargesTable.Annotation = &entsql.Annotation{
		Table: "credit_recharges",
	}
	UserPaymentsTable.Annotation = &entsql.Annotation{
		Table: "user_payments",
	}
}
