// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"store/app/payment/internal/data/repo/ent/creditconsume"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CreditConsume is the model entity for the CreditConsume schema.
type CreditConsume struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// RechargeID holds the value of the "recharge_id" field.
	RechargeID string `json:"recharge_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount       int64 `json:"amount,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreditConsume) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creditconsume.FieldID, creditconsume.FieldAmount:
			values[i] = new(sql.NullInt64)
		case creditconsume.FieldKey, creditconsume.FieldRechargeID, creditconsume.FieldUserID:
			values[i] = new(sql.NullString)
		case creditconsume.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreditConsume fields.
func (cc *CreditConsume) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creditconsume.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cc.ID = int64(value.Int64)
		case creditconsume.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cc.CreatedAt = value.Time
			}
		case creditconsume.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				cc.Key = value.String
			}
		case creditconsume.FieldRechargeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_id", values[i])
			} else if value.Valid {
				cc.RechargeID = value.String
			}
		case creditconsume.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				cc.UserID = value.String
			}
		case creditconsume.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				cc.Amount = value.Int64
			}
		default:
			cc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreditConsume.
// This includes values selected through modifiers, order, etc.
func (cc *CreditConsume) Value(name string) (ent.Value, error) {
	return cc.selectValues.Get(name)
}

// Update returns a builder for updating this CreditConsume.
// Note that you need to call CreditConsume.Unwrap() before calling this method if this CreditConsume
// was returned from a transaction, and the transaction was committed or rolled back.
func (cc *CreditConsume) Update() *CreditConsumeUpdateOne {
	return NewCreditConsumeClient(cc.config).UpdateOne(cc)
}

// Unwrap unwraps the CreditConsume entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cc *CreditConsume) Unwrap() *CreditConsume {
	_tx, ok := cc.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreditConsume is not a transactional entity")
	}
	cc.config.driver = _tx.drv
	return cc
}

// String implements the fmt.Stringer.
func (cc *CreditConsume) String() string {
	var builder strings.Builder
	builder.WriteString("CreditConsume(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(cc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(cc.Key)
	builder.WriteString(", ")
	builder.WriteString("recharge_id=")
	builder.WriteString(cc.RechargeID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(cc.UserID)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", cc.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// CreditConsumes is a parsable slice of CreditConsume.
type CreditConsumes []*CreditConsume
