// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: note/common.proto

package notepb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	_ "store/api/public/response"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Province      string                 `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Area          string                 `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_note_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_note_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_note_common_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type Weather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   string                 `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Precipitation string                 `protobuf:"bytes,2,opt,name=precipitation,proto3" json:"precipitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weather) Reset() {
	*x = Weather{}
	mi := &file_note_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_note_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_note_common_proto_rawDescGZIP(), []int{1}
}

func (x *Weather) GetTemperature() string {
	if x != nil {
		return x.Temperature
	}
	return ""
}

func (x *Weather) GetPrecipitation() string {
	if x != nil {
		return x.Precipitation
	}
	return ""
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_note_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_note_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_note_common_proto_rawDescGZIP(), []int{2}
}

func (x *TimeRange) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *TimeRange) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_note_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_note_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_note_common_proto_rawDescGZIP(), []int{3}
}

func (x *Fee) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_note_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_note_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_note_common_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_note_common_proto protoreflect.FileDescriptor

const file_note_common_proto_rawDesc = "" +
	"\n" +
	"\x11note/common.proto\x12\bapi.note\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1epublic/response/response.proto\x1a\x17validate/validate.proto\x1a\x13note/category.proto\"h\n" +
	"\bLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\x02 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x12\n" +
	"\x04area\x18\x04 \x01(\tR\x04area\"Q\n" +
	"\aWeather\x12 \n" +
	"\vtemperature\x18\x01 \x01(\tR\vtemperature\x12$\n" +
	"\rprecipitation\x18\x02 \x01(\tR\rprecipitation\"7\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x02 \x01(\tR\x05until\"\x1b\n" +
	"\x03Fee\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"\x1b\n" +
	"\x03Tag\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\x17Z\x15store/api/note;notepbb\x06proto3"

var (
	file_note_common_proto_rawDescOnce sync.Once
	file_note_common_proto_rawDescData []byte
)

func file_note_common_proto_rawDescGZIP() []byte {
	file_note_common_proto_rawDescOnce.Do(func() {
		file_note_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_common_proto_rawDesc), len(file_note_common_proto_rawDesc)))
	})
	return file_note_common_proto_rawDescData
}

var file_note_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_note_common_proto_goTypes = []any{
	(*Location)(nil),  // 0: api.note.Location
	(*Weather)(nil),   // 1: api.note.Weather
	(*TimeRange)(nil), // 2: api.note.TimeRange
	(*Fee)(nil),       // 3: api.note.Fee
	(*Tag)(nil),       // 4: api.note.Tag
}
var file_note_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_note_common_proto_init() }
func file_note_common_proto_init() {
	if File_note_common_proto != nil {
		return
	}
	file_note_category_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_common_proto_rawDesc), len(file_note_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_note_common_proto_goTypes,
		DependencyIndexes: file_note_common_proto_depIdxs,
		MessageInfos:      file_note_common_proto_msgTypes,
	}.Build()
	File_note_common_proto = out.File
	file_note_common_proto_goTypes = nil
	file_note_common_proto_depIdxs = nil
}
