// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: note/note_service.proto

package notepb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	_ "store/api/public/response"
	types "store/api/user/types"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeetingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingParams) Reset() {
	*x = GetMeetingParams{}
	mi := &file_note_note_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingParams) ProtoMessage() {}

func (x *GetMeetingParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingParams.ProtoReflect.Descriptor instead.
func (*GetMeetingParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeetingParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateMeetingQuestionParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingQuestionParams) Reset() {
	*x = UpdateMeetingQuestionParams{}
	mi := &file_note_note_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingQuestionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingQuestionParams) ProtoMessage() {}

func (x *UpdateMeetingQuestionParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingQuestionParams.ProtoReflect.Descriptor instead.
func (*UpdateMeetingQuestionParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMeetingQuestionParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMeetingQuestionParams) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AddMeetingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpertId      string                 `protobuf:"bytes,1,opt,name=expertId,proto3" json:"expertId,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	By            string                 `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMeetingParams) Reset() {
	*x = AddMeetingParams{}
	mi := &file_note_note_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMeetingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMeetingParams) ProtoMessage() {}

func (x *AddMeetingParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMeetingParams.ProtoReflect.Descriptor instead.
func (*AddMeetingParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddMeetingParams) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *AddMeetingParams) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AddMeetingParams) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

type Meeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,proto3" json:"_id,omitempty"`
	Expert        *Expert                `protobuf:"bytes,2,opt,name=expert,proto3" json:"expert,omitempty"`
	Topic         *Topic                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	By            string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meeting) Reset() {
	*x = Meeting{}
	mi := &file_note_note_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meeting) ProtoMessage() {}

func (x *Meeting) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meeting.ProtoReflect.Descriptor instead.
func (*Meeting) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{3}
}

func (x *Meeting) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Meeting) GetExpert() *Expert {
	if x != nil {
		return x.Expert
	}
	return nil
}

func (x *Meeting) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Meeting) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *Meeting) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Meeting) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Meeting) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddCommentParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ExpertId      string                 `protobuf:"bytes,3,opt,name=expertId,proto3" json:"expertId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentParams) Reset() {
	*x = AddCommentParams{}
	mi := &file_note_note_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentParams) ProtoMessage() {}

func (x *AddCommentParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentParams.ProtoReflect.Descriptor instead.
func (*AddCommentParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddCommentParams) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *AddCommentParams) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCommentParams) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

type ListCommentsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ExpertId      string                 `protobuf:"bytes,3,opt,name=expertId,proto3" json:"expertId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsParams) Reset() {
	*x = ListCommentsParams{}
	mi := &file_note_note_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsParams) ProtoMessage() {}

func (x *ListCommentsParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsParams.ProtoReflect.Descriptor instead.
func (*ListCommentsParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommentsParams) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsParams) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListCommentsParams) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,proto3" json:"_id,omitempty"`
	User          *types.User            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Expert        *Expert                `protobuf:"bytes,5,opt,name=expert,proto3" json:"expert,omitempty"`
	Meeting       *Meeting               `protobuf:"bytes,6,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_note_note_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{6}
}

func (x *Comment) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Comment) GetUser() *types.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetExpert() *Expert {
	if x != nil {
		return x.Expert
	}
	return nil
}

func (x *Comment) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type CommentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Comment             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentList) Reset() {
	*x = CommentList{}
	mi := &file_note_note_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentList) ProtoMessage() {}

func (x *CommentList) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentList.ProtoReflect.Descriptor instead.
func (*CommentList) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{7}
}

func (x *CommentList) GetList() []*Comment {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CommentList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentList) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *CommentList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetExpertParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpertParams) Reset() {
	*x = GetExpertParams{}
	mi := &file_note_note_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpertParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpertParams) ProtoMessage() {}

func (x *GetExpertParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpertParams.ProtoReflect.Descriptor instead.
func (*GetExpertParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetExpertParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListExpertsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpertsParams) Reset() {
	*x = ListExpertsParams{}
	mi := &file_note_note_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpertsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpertsParams) ProtoMessage() {}

func (x *ListExpertsParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpertsParams.ProtoReflect.Descriptor instead.
func (*ListExpertsParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListExpertsParams) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ExpertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Expert              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertList) Reset() {
	*x = ExpertList{}
	mi := &file_note_note_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertList) ProtoMessage() {}

func (x *ExpertList) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertList.ProtoReflect.Descriptor instead.
func (*ExpertList) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{10}
}

func (x *ExpertList) GetList() []*Expert {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ExpertList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ExpertList) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ExpertList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Expert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,proto3" json:"_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Topics        []*Topic               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	MeetingCount  int64                  `protobuf:"varint,6,opt,name=meetingCount,proto3" json:"meetingCount,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Rating        float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Desc          string                 `protobuf:"bytes,10,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expert) Reset() {
	*x = Expert{}
	mi := &file_note_note_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expert) ProtoMessage() {}

func (x *Expert) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expert.ProtoReflect.Descriptor instead.
func (*Expert) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{11}
}

func (x *Expert) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Expert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Expert) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Expert) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Expert) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Expert) GetMeetingCount() int64 {
	if x != nil {
		return x.MeetingCount
	}
	return 0
}

func (x *Expert) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Expert) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Expert) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Expert) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Expert) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_note_note_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{12}
}

func (x *Topic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddNoteParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteParams) Reset() {
	*x = AddNoteParams{}
	mi := &file_note_note_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteParams) ProtoMessage() {}

func (x *AddNoteParams) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteParams.ProtoReflect.Descriptor instead.
func (*AddNoteParams) Descriptor() ([]byte, []int) {
	return file_note_note_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddNoteParams) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_note_note_service_proto protoreflect.FileDescriptor

const file_note_note_service_proto_rawDesc = "" +
	"\n" +
	"\x17note/note_service.proto\x12\bapi.note\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1epublic/response/response.proto\x1a\x17validate/validate.proto\x1a\x0fnote/note.proto\x1a\x11note/common.proto\x1a\x15user/types/user.proto\"\"\n" +
	"\x10GetMeetingParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x1bUpdateMeetingQuestionParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"T\n" +
	"\x10AddMeetingParams\x12\x1a\n" +
	"\bexpertId\x18\x01 \x01(\tR\bexpertId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\tR\x02by\"\xce\x01\n" +
	"\aMeeting\x12\x10\n" +
	"\x03_id\x18\x01 \x01(\tR\x03_id\x12(\n" +
	"\x06expert\x18\x02 \x01(\v2\x10.api.note.ExpertR\x06expert\x12%\n" +
	"\x05topic\x18\x03 \x01(\v2\x0f.api.note.TopicR\x05topic\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\x03R\tcreatedAt\"f\n" +
	"\x10AddCommentParams\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bexpertId\x18\x03 \x01(\tR\bexpertId\"`\n" +
	"\x12ListCommentsParams\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bexpertId\x18\x03 \x01(\tR\bexpertId\"\xd4\x01\n" +
	"\aComment\x12\x10\n" +
	"\x03_id\x18\x01 \x01(\tR\x03_id\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.api.user.types.UserR\x04user\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12(\n" +
	"\x06expert\x18\x05 \x01(\v2\x10.api.note.ExpertR\x06expert\x12+\n" +
	"\ameeting\x18\x06 \x01(\v2\x11.api.note.MeetingR\ameeting\"x\n" +
	"\vCommentList\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.api.note.CommentR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"!\n" +
	"\x0fGetExpertParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x11ListExpertsParams\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\"v\n" +
	"\n" +
	"ExpertList\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.api.note.ExpertR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"\xac\x02\n" +
	"\x06Expert\x12\x10\n" +
	"\x03_id\x18\x01 \x01(\tR\x03_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12'\n" +
	"\x06topics\x18\x04 \x03(\v2\x0f.api.note.TopicR\x06topics\x12!\n" +
	"\x04tags\x18\x05 \x03(\v2\r.api.note.TagR\x04tags\x12\"\n" +
	"\fmeetingCount\x18\x06 \x01(\x03R\fmeetingCount\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x12\n" +
	"\x04desc\x18\n" +
	" \x01(\tR\x04desc\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\"\x1d\n" +
	"\x05Topic\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"%\n" +
	"\rAddNoteParams\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title2\xc4\x06\n" +
	"\vNoteService\x12L\n" +
	"\x04Test\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/sitemap.xml\x122\n" +
	"\aAddNote\x12\x17.api.note.AddNoteParams\x1a\x0e.api.note.Note\x12\\\n" +
	"\vListExperts\x12\x1b.api.note.ListExpertsParams\x1a\x14.api.note.ExpertList\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/ep/v1/experts\x12Y\n" +
	"\tGetExpert\x12\x19.api.note.GetExpertParams\x1a\x10.api.note.Expert\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/ep/v1/experts/{id}\x12`\n" +
	"\fListComments\x12\x1c.api.note.ListCommentsParams\x1a\x15.api.note.CommentList\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/ep/v1/comments\x12[\n" +
	"\n" +
	"AddComment\x12\x1a.api.note.AddCommentParams\x1a\x11.api.note.Comment\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/ep/v1/comments\x12[\n" +
	"\n" +
	"AddMeeting\x12\x1a.api.note.AddMeetingParams\x1a\x11.api.note.Meeting\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/ep/v1/meetings\x12]\n" +
	"\n" +
	"GetMeeting\x12\x1a.api.note.GetMeetingParams\x1a\x11.api.note.Meeting\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/ep/v1/meetings/{id}\x12\x7f\n" +
	"\x15UpdateMeetingQuestion\x12%.api.note.UpdateMeetingQuestionParams\x1a\x11.api.note.Meeting\",\x82\xd3\xe4\x93\x02&:\x01*2!/api/ep/v1/meetings/{id}/questionB\x17Z\x15store/api/note;notepbb\x06proto3"

var (
	file_note_note_service_proto_rawDescOnce sync.Once
	file_note_note_service_proto_rawDescData []byte
)

func file_note_note_service_proto_rawDescGZIP() []byte {
	file_note_note_service_proto_rawDescOnce.Do(func() {
		file_note_note_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_note_service_proto_rawDesc), len(file_note_note_service_proto_rawDesc)))
	})
	return file_note_note_service_proto_rawDescData
}

var file_note_note_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_note_note_service_proto_goTypes = []any{
	(*GetMeetingParams)(nil),            // 0: api.note.GetMeetingParams
	(*UpdateMeetingQuestionParams)(nil), // 1: api.note.UpdateMeetingQuestionParams
	(*AddMeetingParams)(nil),            // 2: api.note.AddMeetingParams
	(*Meeting)(nil),                     // 3: api.note.Meeting
	(*AddCommentParams)(nil),            // 4: api.note.AddCommentParams
	(*ListCommentsParams)(nil),          // 5: api.note.ListCommentsParams
	(*Comment)(nil),                     // 6: api.note.Comment
	(*CommentList)(nil),                 // 7: api.note.CommentList
	(*GetExpertParams)(nil),             // 8: api.note.GetExpertParams
	(*ListExpertsParams)(nil),           // 9: api.note.ListExpertsParams
	(*ExpertList)(nil),                  // 10: api.note.ExpertList
	(*Expert)(nil),                      // 11: api.note.Expert
	(*Topic)(nil),                       // 12: api.note.Topic
	(*AddNoteParams)(nil),               // 13: api.note.AddNoteParams
	(*types.User)(nil),                  // 14: api.user.types.User
	(*Tag)(nil),                         // 15: api.note.Tag
	(*emptypb.Empty)(nil),               // 16: google.protobuf.Empty
	(*Note)(nil),                        // 17: api.note.Note
}
var file_note_note_service_proto_depIdxs = []int32{
	11, // 0: api.note.Meeting.expert:type_name -> api.note.Expert
	12, // 1: api.note.Meeting.topic:type_name -> api.note.Topic
	14, // 2: api.note.Comment.user:type_name -> api.user.types.User
	11, // 3: api.note.Comment.expert:type_name -> api.note.Expert
	3,  // 4: api.note.Comment.meeting:type_name -> api.note.Meeting
	6,  // 5: api.note.CommentList.list:type_name -> api.note.Comment
	11, // 6: api.note.ExpertList.list:type_name -> api.note.Expert
	12, // 7: api.note.Expert.topics:type_name -> api.note.Topic
	15, // 8: api.note.Expert.tags:type_name -> api.note.Tag
	16, // 9: api.note.NoteService.Test:input_type -> google.protobuf.Empty
	13, // 10: api.note.NoteService.AddNote:input_type -> api.note.AddNoteParams
	9,  // 11: api.note.NoteService.ListExperts:input_type -> api.note.ListExpertsParams
	8,  // 12: api.note.NoteService.GetExpert:input_type -> api.note.GetExpertParams
	5,  // 13: api.note.NoteService.ListComments:input_type -> api.note.ListCommentsParams
	4,  // 14: api.note.NoteService.AddComment:input_type -> api.note.AddCommentParams
	2,  // 15: api.note.NoteService.AddMeeting:input_type -> api.note.AddMeetingParams
	0,  // 16: api.note.NoteService.GetMeeting:input_type -> api.note.GetMeetingParams
	1,  // 17: api.note.NoteService.UpdateMeetingQuestion:input_type -> api.note.UpdateMeetingQuestionParams
	16, // 18: api.note.NoteService.Test:output_type -> google.protobuf.Empty
	17, // 19: api.note.NoteService.AddNote:output_type -> api.note.Note
	10, // 20: api.note.NoteService.ListExperts:output_type -> api.note.ExpertList
	11, // 21: api.note.NoteService.GetExpert:output_type -> api.note.Expert
	7,  // 22: api.note.NoteService.ListComments:output_type -> api.note.CommentList
	6,  // 23: api.note.NoteService.AddComment:output_type -> api.note.Comment
	3,  // 24: api.note.NoteService.AddMeeting:output_type -> api.note.Meeting
	3,  // 25: api.note.NoteService.GetMeeting:output_type -> api.note.Meeting
	3,  // 26: api.note.NoteService.UpdateMeetingQuestion:output_type -> api.note.Meeting
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_note_note_service_proto_init() }
func file_note_note_service_proto_init() {
	if File_note_note_service_proto != nil {
		return
	}
	file_note_note_proto_init()
	file_note_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_note_service_proto_rawDesc), len(file_note_note_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_note_service_proto_goTypes,
		DependencyIndexes: file_note_note_service_proto_depIdxs,
		MessageInfos:      file_note_note_service_proto_msgTypes,
	}.Build()
	File_note_note_service_proto = out.File
	file_note_note_service_proto_goTypes = nil
	file_note_note_service_proto_depIdxs = nil
}
