// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: note/note_service.proto

package notepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteService_Test_FullMethodName                  = "/api.note.NoteService/Test"
	NoteService_AddNote_FullMethodName               = "/api.note.NoteService/AddNote"
	NoteService_ListExperts_FullMethodName           = "/api.note.NoteService/ListExperts"
	NoteService_GetExpert_FullMethodName             = "/api.note.NoteService/GetExpert"
	NoteService_ListComments_FullMethodName          = "/api.note.NoteService/ListComments"
	NoteService_AddComment_FullMethodName            = "/api.note.NoteService/AddComment"
	NoteService_AddMeeting_FullMethodName            = "/api.note.NoteService/AddMeeting"
	NoteService_GetMeeting_FullMethodName            = "/api.note.NoteService/GetMeeting"
	NoteService_UpdateMeetingQuestion_FullMethodName = "/api.note.NoteService/UpdateMeetingQuestion"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	Test(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddNote(ctx context.Context, in *AddNoteParams, opts ...grpc.CallOption) (*Note, error)
	ListExperts(ctx context.Context, in *ListExpertsParams, opts ...grpc.CallOption) (*ExpertList, error)
	GetExpert(ctx context.Context, in *GetExpertParams, opts ...grpc.CallOption) (*Expert, error)
	ListComments(ctx context.Context, in *ListCommentsParams, opts ...grpc.CallOption) (*CommentList, error)
	AddComment(ctx context.Context, in *AddCommentParams, opts ...grpc.CallOption) (*Comment, error)
	AddMeeting(ctx context.Context, in *AddMeetingParams, opts ...grpc.CallOption) (*Meeting, error)
	GetMeeting(ctx context.Context, in *GetMeetingParams, opts ...grpc.CallOption) (*Meeting, error)
	UpdateMeetingQuestion(ctx context.Context, in *UpdateMeetingQuestionParams, opts ...grpc.CallOption) (*Meeting, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) Test(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NoteService_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) AddNote(ctx context.Context, in *AddNoteParams, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteService_AddNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListExperts(ctx context.Context, in *ListExpertsParams, opts ...grpc.CallOption) (*ExpertList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpertList)
	err := c.cc.Invoke(ctx, NoteService_ListExperts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetExpert(ctx context.Context, in *GetExpertParams, opts ...grpc.CallOption) (*Expert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Expert)
	err := c.cc.Invoke(ctx, NoteService_GetExpert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListComments(ctx context.Context, in *ListCommentsParams, opts ...grpc.CallOption) (*CommentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentList)
	err := c.cc.Invoke(ctx, NoteService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) AddComment(ctx context.Context, in *AddCommentParams, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, NoteService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) AddMeeting(ctx context.Context, in *AddMeetingParams, opts ...grpc.CallOption) (*Meeting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meeting)
	err := c.cc.Invoke(ctx, NoteService_AddMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetMeeting(ctx context.Context, in *GetMeetingParams, opts ...grpc.CallOption) (*Meeting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meeting)
	err := c.cc.Invoke(ctx, NoteService_GetMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateMeetingQuestion(ctx context.Context, in *UpdateMeetingQuestionParams, opts ...grpc.CallOption) (*Meeting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Meeting)
	err := c.cc.Invoke(ctx, NoteService_UpdateMeetingQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility.
type NoteServiceServer interface {
	Test(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AddNote(context.Context, *AddNoteParams) (*Note, error)
	ListExperts(context.Context, *ListExpertsParams) (*ExpertList, error)
	GetExpert(context.Context, *GetExpertParams) (*Expert, error)
	ListComments(context.Context, *ListCommentsParams) (*CommentList, error)
	AddComment(context.Context, *AddCommentParams) (*Comment, error)
	AddMeeting(context.Context, *AddMeetingParams) (*Meeting, error)
	GetMeeting(context.Context, *GetMeetingParams) (*Meeting, error)
	UpdateMeetingQuestion(context.Context, *UpdateMeetingQuestionParams) (*Meeting, error)
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteServiceServer struct{}

func (UnimplementedNoteServiceServer) Test(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedNoteServiceServer) AddNote(context.Context, *AddNoteParams) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNote not implemented")
}
func (UnimplementedNoteServiceServer) ListExperts(context.Context, *ListExpertsParams) (*ExpertList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExperts not implemented")
}
func (UnimplementedNoteServiceServer) GetExpert(context.Context, *GetExpertParams) (*Expert, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpert not implemented")
}
func (UnimplementedNoteServiceServer) ListComments(context.Context, *ListCommentsParams) (*CommentList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedNoteServiceServer) AddComment(context.Context, *AddCommentParams) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedNoteServiceServer) AddMeeting(context.Context, *AddMeetingParams) (*Meeting, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMeeting not implemented")
}
func (UnimplementedNoteServiceServer) GetMeeting(context.Context, *GetMeetingParams) (*Meeting, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeeting not implemented")
}
func (UnimplementedNoteServiceServer) UpdateMeetingQuestion(context.Context, *UpdateMeetingQuestionParams) (*Meeting, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMeetingQuestion not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}
func (UnimplementedNoteServiceServer) testEmbeddedByValue()                     {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	// If the following call panics, it indicates UnimplementedNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Test(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_AddNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNoteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).AddNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_AddNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).AddNote(ctx, req.(*AddNoteParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListExperts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpertsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListExperts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListExperts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListExperts(ctx, req.(*ListExpertsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetExpert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpertParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetExpert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetExpert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetExpert(ctx, req.(*GetExpertParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListComments(ctx, req.(*ListCommentsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).AddComment(ctx, req.(*AddCommentParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_AddMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMeetingParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).AddMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_AddMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).AddMeeting(ctx, req.(*AddMeetingParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetMeeting(ctx, req.(*GetMeetingParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateMeetingQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeetingQuestionParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateMeetingQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateMeetingQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateMeetingQuestion(ctx, req.(*UpdateMeetingQuestionParams))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.note.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _NoteService_Test_Handler,
		},
		{
			MethodName: "AddNote",
			Handler:    _NoteService_AddNote_Handler,
		},
		{
			MethodName: "ListExperts",
			Handler:    _NoteService_ListExperts_Handler,
		},
		{
			MethodName: "GetExpert",
			Handler:    _NoteService_GetExpert_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _NoteService_ListComments_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _NoteService_AddComment_Handler,
		},
		{
			MethodName: "AddMeeting",
			Handler:    _NoteService_AddMeeting_Handler,
		},
		{
			MethodName: "GetMeeting",
			Handler:    _NoteService_GetMeeting_Handler,
		},
		{
			MethodName: "UpdateMeetingQuestion",
			Handler:    _NoteService_UpdateMeetingQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "note/note_service.proto",
}
