# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pro
  region: cn-north-1

nodeGroups:
  - name: 1c2g-t2small
    instanceType: t2.small
    minSize: 2
    maxSize: 4
    desiredCapacity: 2

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"