// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"store/app/usercenter/configs"
	"store/app/usercenter/internal/biz"
	"store/app/usercenter/internal/data"
	"store/app/usercenter/internal/server"
	"store/app/usercenter/internal/service"
	"store/pkg/confcenter"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(config confcenter.Config[configs.BizConfig], meta confcenter.Meta, confcenterServer confcenter.Server, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(config)
	if err != nil {
		return nil, nil, err
	}
	itemBiz := biz.NewItemBiz(dataData)
	userService := service.NewUserService(dataData, itemBiz)
	authService := service.NewAuthService(dataData, itemBiz)
	toolkitService := service.NewToolkitService(dataData, itemBiz)
	creditService := service.NewCreditService(dataData, itemBiz)
	grpcServer := server.NewGRPCServer(confcenterServer, userService, authService, toolkitService, creditService, logger)
	httpServer := server.NewHTTPServer(confcenterServer, userService, authService, toolkitService, creditService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
