// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: demo/bar_service.proto

// AI 提示：这是项目中的第二个 Service 文件（BarService）。
// 每种资源有自己的 service。

package demopb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FooId         string                 `protobuf:"bytes,1,opt,name=fooId,proto3" json:"fooId,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBarRequest) Reset() {
	*x = CreateBarRequest{}
	mi := &file_demo_bar_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarRequest) ProtoMessage() {}

func (x *CreateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarRequest.ProtoReflect.Descriptor instead.
func (*CreateBarRequest) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBarRequest) GetFooId() string {
	if x != nil {
		return x.FooId
	}
	return ""
}

func (x *CreateBarRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarRequest) Reset() {
	*x = GetBarRequest{}
	mi := &file_demo_bar_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarRequest) ProtoMessage() {}

func (x *GetBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarRequest.ProtoReflect.Descriptor instead.
func (*GetBarRequest) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBarRequest) Reset() {
	*x = UpdateBarRequest{}
	mi := &file_demo_bar_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarRequest) ProtoMessage() {}

func (x *UpdateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarRequest.ProtoReflect.Descriptor instead.
func (*UpdateBarRequest) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBarRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateBarRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarRequest) Reset() {
	*x = DeleteBarRequest{}
	mi := &file_demo_bar_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarRequest) ProtoMessage() {}

func (x *DeleteBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarRequest.ProtoReflect.Descriptor instead.
func (*DeleteBarRequest) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	FooId         string                 `protobuf:"bytes,3,opt,name=fooId,proto3" json:"fooId,omitempty"` // 过滤条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarsRequest) Reset() {
	*x = ListBarsRequest{}
	mi := &file_demo_bar_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarsRequest) ProtoMessage() {}

func (x *ListBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarsRequest.ProtoReflect.Descriptor instead.
func (*ListBarsRequest) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListBarsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBarsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListBarsRequest) GetFooId() string {
	if x != nil {
		return x.FooId
	}
	return ""
}

type BarList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Bar                 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarList) Reset() {
	*x = BarList{}
	mi := &file_demo_bar_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarList) ProtoMessage() {}

func (x *BarList) ProtoReflect() protoreflect.Message {
	mi := &file_demo_bar_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarList.ProtoReflect.Descriptor instead.
func (*BarList) Descriptor() ([]byte, []int) {
	return file_demo_bar_service_proto_rawDescGZIP(), []int{5}
}

func (x *BarList) GetList() []*Bar {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *BarList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_demo_bar_service_proto protoreflect.FileDescriptor

const file_demo_bar_service_proto_rawDesc = "" +
	"\n" +
	"\x16demo/bar_service.proto\x12\bapi.demo\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0edemo/foo.proto\x1a\x0edemo/bar.proto\"\xa3\x01\n" +
	"\x10CreateBarRequest\x12\x14\n" +
	"\x05fooId\x18\x01 \x01(\tR\x05fooId\x12>\n" +
	"\x06config\x18\x02 \x03(\v2&.api.demo.CreateBarRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\rGetBarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb5\x01\n" +
	"\x10UpdateBarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12>\n" +
	"\x06config\x18\x03 \x03(\v2&.api.demo.UpdateBarRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\x10DeleteBarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x0fListBarsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05fooId\x18\x03 \x01(\tR\x05fooId\"B\n" +
	"\aBarList\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.api.demo.BarR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xac\x03\n" +
	"\n" +
	"BarService\x12O\n" +
	"\tCreateBar\x12\x1a.api.demo.CreateBarRequest\x1a\r.api.demo.Bar\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/ba/bars\x12K\n" +
	"\x06GetBar\x12\x17.api.demo.GetBarRequest\x1a\r.api.demo.Bar\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/ba/bars/{id}\x12T\n" +
	"\tUpdateBar\x12\x1a.api.demo.UpdateBarRequest\x1a\r.api.demo.Bar\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/api/ba/bars/{id}\x12Z\n" +
	"\tDeleteBar\x12\x1a.api.demo.DeleteBarRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/ba/bars/{id}\x12N\n" +
	"\bListBars\x12\x19.api.demo.ListBarsRequest\x1a\x11.api.demo.BarList\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/ba/barsB\x17Z\x15store/api/demo;demopbb\x06proto3"

var (
	file_demo_bar_service_proto_rawDescOnce sync.Once
	file_demo_bar_service_proto_rawDescData []byte
)

func file_demo_bar_service_proto_rawDescGZIP() []byte {
	file_demo_bar_service_proto_rawDescOnce.Do(func() {
		file_demo_bar_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_bar_service_proto_rawDesc), len(file_demo_bar_service_proto_rawDesc)))
	})
	return file_demo_bar_service_proto_rawDescData
}

var file_demo_bar_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_demo_bar_service_proto_goTypes = []any{
	(*CreateBarRequest)(nil), // 0: api.demo.CreateBarRequest
	(*GetBarRequest)(nil),    // 1: api.demo.GetBarRequest
	(*UpdateBarRequest)(nil), // 2: api.demo.UpdateBarRequest
	(*DeleteBarRequest)(nil), // 3: api.demo.DeleteBarRequest
	(*ListBarsRequest)(nil),  // 4: api.demo.ListBarsRequest
	(*BarList)(nil),          // 5: api.demo.BarList
	nil,                      // 6: api.demo.CreateBarRequest.ConfigEntry
	nil,                      // 7: api.demo.UpdateBarRequest.ConfigEntry
	(*Bar)(nil),              // 8: api.demo.Bar
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_demo_bar_service_proto_depIdxs = []int32{
	6, // 0: api.demo.CreateBarRequest.config:type_name -> api.demo.CreateBarRequest.ConfigEntry
	7, // 1: api.demo.UpdateBarRequest.config:type_name -> api.demo.UpdateBarRequest.ConfigEntry
	8, // 2: api.demo.BarList.list:type_name -> api.demo.Bar
	0, // 3: api.demo.BarService.CreateBar:input_type -> api.demo.CreateBarRequest
	1, // 4: api.demo.BarService.GetBar:input_type -> api.demo.GetBarRequest
	2, // 5: api.demo.BarService.UpdateBar:input_type -> api.demo.UpdateBarRequest
	3, // 6: api.demo.BarService.DeleteBar:input_type -> api.demo.DeleteBarRequest
	4, // 7: api.demo.BarService.ListBars:input_type -> api.demo.ListBarsRequest
	8, // 8: api.demo.BarService.CreateBar:output_type -> api.demo.Bar
	8, // 9: api.demo.BarService.GetBar:output_type -> api.demo.Bar
	8, // 10: api.demo.BarService.UpdateBar:output_type -> api.demo.Bar
	9, // 11: api.demo.BarService.DeleteBar:output_type -> google.protobuf.Empty
	5, // 12: api.demo.BarService.ListBars:output_type -> api.demo.BarList
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_demo_bar_service_proto_init() }
func file_demo_bar_service_proto_init() {
	if File_demo_bar_service_proto != nil {
		return
	}
	file_demo_foo_proto_init()
	file_demo_bar_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_bar_service_proto_rawDesc), len(file_demo_bar_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_bar_service_proto_goTypes,
		DependencyIndexes: file_demo_bar_service_proto_depIdxs,
		MessageInfos:      file_demo_bar_service_proto_msgTypes,
	}.Build()
	File_demo_bar_service_proto = out.File
	file_demo_bar_service_proto_goTypes = nil
	file_demo_bar_service_proto_depIdxs = nil
}
