// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: demo/bar_service.proto

package demopb

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBarServiceCreateBar = "/api.demo.BarService/CreateBar"
const OperationBarServiceDeleteBar = "/api.demo.BarService/DeleteBar"
const OperationBarServiceGetBar = "/api.demo.BarService/GetBar"
const OperationBarServiceListBars = "/api.demo.BarService/ListBars"
const OperationBarServiceUpdateBar = "/api.demo.BarService/UpdateBar"

type BarServiceHTTPServer interface {
	// CreateBar CreateBar: 创建一个新的 Bar。
	CreateBar(context.Context, *CreateBarRequest) (*Bar, error)
	// DeleteBar DeleteBar: 删除 Bar。
	DeleteBar(context.Context, *DeleteBarRequest) (*emptypb.Empty, error)
	// GetBar GetBar: 获取 Bar 详情。
	GetBar(context.Context, *GetBarRequest) (*Bar, error)
	// ListBars ListBars: 获取 Bar 列表。
	ListBars(context.Context, *ListBarsRequest) (*BarList, error)
	// UpdateBar UpdateBar: 修改 Bar。
	UpdateBar(context.Context, *UpdateBarRequest) (*Bar, error)
}

func RegisterBarServiceHTTPServer(s *http.Server, srv BarServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/ba/bars", _BarService_CreateBar0_HTTP_Handler(srv))
	r.GET("/api/ba/bars/{id}", _BarService_GetBar0_HTTP_Handler(srv))
	r.PATCH("/api/ba/bars/{id}", _BarService_UpdateBar0_HTTP_Handler(srv))
	r.DELETE("/api/ba/bars/{id}", _BarService_DeleteBar0_HTTP_Handler(srv))
	r.GET("/api/ba/bars", _BarService_ListBars0_HTTP_Handler(srv))
}

func _BarService_CreateBar0_HTTP_Handler(srv BarServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBarServiceCreateBar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBar(ctx, req.(*CreateBarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Bar)
		return ctx.Result(200, reply)
	}
}

func _BarService_GetBar0_HTTP_Handler(srv BarServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBarRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBarServiceGetBar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBar(ctx, req.(*GetBarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Bar)
		return ctx.Result(200, reply)
	}
}

func _BarService_UpdateBar0_HTTP_Handler(srv BarServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBarServiceUpdateBar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBar(ctx, req.(*UpdateBarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Bar)
		return ctx.Result(200, reply)
	}
}

func _BarService_DeleteBar0_HTTP_Handler(srv BarServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBarRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBarServiceDeleteBar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBar(ctx, req.(*DeleteBarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BarService_ListBars0_HTTP_Handler(srv BarServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBarsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBarServiceListBars)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBars(ctx, req.(*ListBarsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BarList)
		return ctx.Result(200, reply)
	}
}

type BarServiceHTTPClient interface {
	// CreateBar CreateBar: 创建一个新的 Bar。
	CreateBar(ctx context.Context, req *CreateBarRequest, opts ...http.CallOption) (rsp *Bar, err error)
	// DeleteBar DeleteBar: 删除 Bar。
	DeleteBar(ctx context.Context, req *DeleteBarRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetBar GetBar: 获取 Bar 详情。
	GetBar(ctx context.Context, req *GetBarRequest, opts ...http.CallOption) (rsp *Bar, err error)
	// ListBars ListBars: 获取 Bar 列表。
	ListBars(ctx context.Context, req *ListBarsRequest, opts ...http.CallOption) (rsp *BarList, err error)
	// UpdateBar UpdateBar: 修改 Bar。
	UpdateBar(ctx context.Context, req *UpdateBarRequest, opts ...http.CallOption) (rsp *Bar, err error)
}

type BarServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBarServiceHTTPClient(client *http.Client) BarServiceHTTPClient {
	return &BarServiceHTTPClientImpl{client}
}

// CreateBar CreateBar: 创建一个新的 Bar。
func (c *BarServiceHTTPClientImpl) CreateBar(ctx context.Context, in *CreateBarRequest, opts ...http.CallOption) (*Bar, error) {
	var out Bar
	pattern := "/api/ba/bars"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBarServiceCreateBar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteBar DeleteBar: 删除 Bar。
func (c *BarServiceHTTPClientImpl) DeleteBar(ctx context.Context, in *DeleteBarRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/ba/bars/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBarServiceDeleteBar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetBar GetBar: 获取 Bar 详情。
func (c *BarServiceHTTPClientImpl) GetBar(ctx context.Context, in *GetBarRequest, opts ...http.CallOption) (*Bar, error) {
	var out Bar
	pattern := "/api/ba/bars/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBarServiceGetBar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBars ListBars: 获取 Bar 列表。
func (c *BarServiceHTTPClientImpl) ListBars(ctx context.Context, in *ListBarsRequest, opts ...http.CallOption) (*BarList, error) {
	var out BarList
	pattern := "/api/ba/bars"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBarServiceListBars))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateBar UpdateBar: 修改 Bar。
func (c *BarServiceHTTPClientImpl) UpdateBar(ctx context.Context, in *UpdateBarRequest, opts ...http.CallOption) (*Bar, error) {
	var out Bar
	pattern := "/api/ba/bars/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBarServiceUpdateBar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
