// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: dex/commission.proto

package dexpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Commission with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Commission) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Commission with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommissionMultiError, or
// nil if none found.
func (m *Commission) ValidateAll() error {
	return m.validate(true)
}

func (m *Commission) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rate

	// no validation rules for ToUserId

	// no validation rules for ValidInvitedUserCount

	if len(errors) > 0 {
		return CommissionMultiError(errors)
	}

	return nil
}

// CommissionMultiError is an error wrapping multiple validation errors
// returned by Commission.ValidateAll() if the designated constraints aren't met.
type CommissionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommissionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommissionMultiError) AllErrors() []error { return m }

// CommissionValidationError is the validation error returned by
// Commission.Validate if the designated constraints aren't met.
type CommissionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommissionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommissionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommissionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommissionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommissionValidationError) ErrorName() string { return "CommissionValidationError" }

// Error satisfies the builtin error interface
func (e CommissionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommission.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommissionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommissionValidationError{}

// Validate checks the field values on Apply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Apply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Apply with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ApplyMultiError, or nil if none found.
func (m *Apply) ValidateAll() error {
	return m.validate(true)
}

func (m *Apply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for At

	if len(errors) > 0 {
		return ApplyMultiError(errors)
	}

	return nil
}

// ApplyMultiError is an error wrapping multiple validation errors returned by
// Apply.ValidateAll() if the designated constraints aren't met.
type ApplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApplyMultiError) AllErrors() []error { return m }

// ApplyValidationError is the validation error returned by Apply.Validate if
// the designated constraints aren't met.
type ApplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplyValidationError) ErrorName() string { return "ApplyValidationError" }

// Error satisfies the builtin error interface
func (e ApplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplyValidationError{}

// Validate checks the field values on Approve with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Approve) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Approve with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ApproveMultiError, or nil if none found.
func (m *Approve) ValidateAll() error {
	return m.validate(true)
}

func (m *Approve) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for At

	// no validation rules for TxHash

	if len(errors) > 0 {
		return ApproveMultiError(errors)
	}

	return nil
}

// ApproveMultiError is an error wrapping multiple validation errors returned
// by Approve.ValidateAll() if the designated constraints aren't met.
type ApproveMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApproveMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApproveMultiError) AllErrors() []error { return m }

// ApproveValidationError is the validation error returned by Approve.Validate
// if the designated constraints aren't met.
type ApproveValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApproveValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApproveValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApproveValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApproveValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApproveValidationError) ErrorName() string { return "ApproveValidationError" }

// Error satisfies the builtin error interface
func (e ApproveValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApprove.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApproveValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApproveValidationError{}

// Validate checks the field values on Reject with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Reject) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Reject with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RejectMultiError, or nil if none found.
func (m *Reject) ValidateAll() error {
	return m.validate(true)
}

func (m *Reject) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for At

	// no validation rules for Reason

	if len(errors) > 0 {
		return RejectMultiError(errors)
	}

	return nil
}

// RejectMultiError is an error wrapping multiple validation errors returned by
// Reject.ValidateAll() if the designated constraints aren't met.
type RejectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RejectMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RejectMultiError) AllErrors() []error { return m }

// RejectValidationError is the validation error returned by Reject.Validate if
// the designated constraints aren't met.
type RejectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RejectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RejectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RejectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RejectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RejectValidationError) ErrorName() string { return "RejectValidationError" }

// Error satisfies the builtin error interface
func (e RejectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RejectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RejectValidationError{}

// Validate checks the field values on CommissionSettlement with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommissionSettlement) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommissionSettlement with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommissionSettlementMultiError, or nil if none found.
func (m *CommissionSettlement) ValidateAll() error {
	return m.validate(true)
}

func (m *CommissionSettlement) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTimeRange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "TimeRange",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimeRange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "TimeRange",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCategory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Category",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Token",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMeta()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMeta()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Meta",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetApply()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Apply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Apply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetApply()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Apply",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetApprove()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Approve",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommissionSettlementValidationError{
					field:  "Approve",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetApprove()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommissionSettlementValidationError{
				field:  "Approve",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommissionSettlementMultiError(errors)
	}

	return nil
}

// CommissionSettlementMultiError is an error wrapping multiple validation
// errors returned by CommissionSettlement.ValidateAll() if the designated
// constraints aren't met.
type CommissionSettlementMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommissionSettlementMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommissionSettlementMultiError) AllErrors() []error { return m }

// CommissionSettlementValidationError is the validation error returned by
// CommissionSettlement.Validate if the designated constraints aren't met.
type CommissionSettlementValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommissionSettlementValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommissionSettlementValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommissionSettlementValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommissionSettlementValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommissionSettlementValidationError) ErrorName() string {
	return "CommissionSettlementValidationError"
}

// Error satisfies the builtin error interface
func (e CommissionSettlementValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommissionSettlement.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommissionSettlementValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommissionSettlementValidationError{}

// Validate checks the field values on Withdrawal with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Withdrawal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Withdrawal with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WithdrawalMultiError, or
// nil if none found.
func (m *Withdrawal) ValidateAll() error {
	return m.validate(true)
}

func (m *Withdrawal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "Token",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetApply()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Apply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Apply",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetApply()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "Apply",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetApprove()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Approve",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WithdrawalValidationError{
					field:  "Approve",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetApprove()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WithdrawalValidationError{
				field:  "Approve",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WithdrawalMultiError(errors)
	}

	return nil
}

// WithdrawalMultiError is an error wrapping multiple validation errors
// returned by Withdrawal.ValidateAll() if the designated constraints aren't met.
type WithdrawalMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawalMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawalMultiError) AllErrors() []error { return m }

// WithdrawalValidationError is the validation error returned by
// Withdrawal.Validate if the designated constraints aren't met.
type WithdrawalValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawalValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawalValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawalValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawalValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawalValidationError) ErrorName() string { return "WithdrawalValidationError" }

// Error satisfies the builtin error interface
func (e WithdrawalValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawalValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawalValidationError{}

// Validate checks the field values on WithdrawalList with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WithdrawalList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WithdrawalList with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WithdrawalListMultiError,
// or nil if none found.
func (m *WithdrawalList) ValidateAll() error {
	return m.validate(true)
}

func (m *WithdrawalList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WithdrawalListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WithdrawalListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WithdrawalListValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WithdrawalListMultiError(errors)
	}

	return nil
}

// WithdrawalListMultiError is an error wrapping multiple validation errors
// returned by WithdrawalList.ValidateAll() if the designated constraints
// aren't met.
type WithdrawalListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WithdrawalListMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WithdrawalListMultiError) AllErrors() []error { return m }

// WithdrawalListValidationError is the validation error returned by
// WithdrawalList.Validate if the designated constraints aren't met.
type WithdrawalListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WithdrawalListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WithdrawalListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WithdrawalListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WithdrawalListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WithdrawalListValidationError) ErrorName() string { return "WithdrawalListValidationError" }

// Error satisfies the builtin error interface
func (e WithdrawalListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWithdrawalList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WithdrawalListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WithdrawalListValidationError{}

// Validate checks the field values on CommissionSettlement_Meta with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommissionSettlement_Meta) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommissionSettlement_Meta with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommissionSettlement_MetaMultiError, or nil if none found.
func (m *CommissionSettlement_Meta) ValidateAll() error {
	return m.validate(true)
}

func (m *CommissionSettlement_Meta) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderAmount

	// no validation rules for OrderFeeAmount

	// no validation rules for OrderCount

	// no validation rules for UserCount

	// no validation rules for Rate

	if len(errors) > 0 {
		return CommissionSettlement_MetaMultiError(errors)
	}

	return nil
}

// CommissionSettlement_MetaMultiError is an error wrapping multiple validation
// errors returned by CommissionSettlement_Meta.ValidateAll() if the
// designated constraints aren't met.
type CommissionSettlement_MetaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommissionSettlement_MetaMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommissionSettlement_MetaMultiError) AllErrors() []error { return m }

// CommissionSettlement_MetaValidationError is the validation error returned by
// CommissionSettlement_Meta.Validate if the designated constraints aren't met.
type CommissionSettlement_MetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommissionSettlement_MetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommissionSettlement_MetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommissionSettlement_MetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommissionSettlement_MetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommissionSettlement_MetaValidationError) ErrorName() string {
	return "CommissionSettlement_MetaValidationError"
}

// Error satisfies the builtin error interface
func (e CommissionSettlement_MetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommissionSettlement_Meta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommissionSettlement_MetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommissionSettlement_MetaValidationError{}
