// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: dex/market_service.proto

package dexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_ListTokens_FullMethodName                   = "/api.dex.MarketService/ListTokens"
	MarketService_GetToken_FullMethodName                     = "/api.dex.MarketService/GetToken"
	MarketService_ListTokenTrades_FullMethodName              = "/api.dex.MarketService/ListTokenTrades"
	MarketService_ListFollowingTrades_FullMethodName          = "/api.dex.MarketService/ListFollowingTrades"
	MarketService_CollectTokens_FullMethodName                = "/api.dex.MarketService/CollectTokens"
	MarketService_CollectTrades_FullMethodName                = "/api.dex.MarketService/CollectTrades"
	MarketService_RunTask_FullMethodName                      = "/api.dex.MarketService/RunTask"
	MarketService_ListPublicFollowingWallets_FullMethodName   = "/api.dex.MarketService/ListPublicFollowingWallets"
	MarketService_UpdatePublicFollowingWallets_FullMethodName = "/api.dex.MarketService/UpdatePublicFollowingWallets"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	ListTokens(ctx context.Context, in *ListTokensParams, opts ...grpc.CallOption) (*TokenList, error)
	GetToken(ctx context.Context, in *GetTokenParams, opts ...grpc.CallOption) (*Token, error)
	ListTokenTrades(ctx context.Context, in *ListTokenTradesParams, opts ...grpc.CallOption) (*TradeList, error)
	// activities
	ListFollowingTrades(ctx context.Context, in *ListFollowingTradesParams, opts ...grpc.CallOption) (*TradeList, error)
	CollectTokens(ctx context.Context, in *CollectTokensParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CollectTrades(ctx context.Context, in *CollectTradesParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RunTask(ctx context.Context, in *RunTaskParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPublicFollowingWallets(ctx context.Context, in *ListPublicFollowingWalletsParams, opts ...grpc.CallOption) (*WalletList, error)
	UpdatePublicFollowingWallets(ctx context.Context, in *UpdatePublicFollowingWalletsParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) ListTokens(ctx context.Context, in *ListTokensParams, opts ...grpc.CallOption) (*TokenList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenList)
	err := c.cc.Invoke(ctx, MarketService_ListTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetToken(ctx context.Context, in *GetTokenParams, opts ...grpc.CallOption) (*Token, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Token)
	err := c.cc.Invoke(ctx, MarketService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListTokenTrades(ctx context.Context, in *ListTokenTradesParams, opts ...grpc.CallOption) (*TradeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeList)
	err := c.cc.Invoke(ctx, MarketService_ListTokenTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListFollowingTrades(ctx context.Context, in *ListFollowingTradesParams, opts ...grpc.CallOption) (*TradeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeList)
	err := c.cc.Invoke(ctx, MarketService_ListFollowingTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) CollectTokens(ctx context.Context, in *CollectTokensParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MarketService_CollectTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) CollectTrades(ctx context.Context, in *CollectTradesParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MarketService_CollectTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) RunTask(ctx context.Context, in *RunTaskParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MarketService_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ListPublicFollowingWallets(ctx context.Context, in *ListPublicFollowingWalletsParams, opts ...grpc.CallOption) (*WalletList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletList)
	err := c.cc.Invoke(ctx, MarketService_ListPublicFollowingWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) UpdatePublicFollowingWallets(ctx context.Context, in *UpdatePublicFollowingWalletsParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MarketService_UpdatePublicFollowingWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
type MarketServiceServer interface {
	ListTokens(context.Context, *ListTokensParams) (*TokenList, error)
	GetToken(context.Context, *GetTokenParams) (*Token, error)
	ListTokenTrades(context.Context, *ListTokenTradesParams) (*TradeList, error)
	// activities
	ListFollowingTrades(context.Context, *ListFollowingTradesParams) (*TradeList, error)
	CollectTokens(context.Context, *CollectTokensParams) (*emptypb.Empty, error)
	CollectTrades(context.Context, *CollectTradesParams) (*emptypb.Empty, error)
	RunTask(context.Context, *RunTaskParams) (*emptypb.Empty, error)
	ListPublicFollowingWallets(context.Context, *ListPublicFollowingWalletsParams) (*WalletList, error)
	UpdatePublicFollowingWallets(context.Context, *UpdatePublicFollowingWalletsParams) (*emptypb.Empty, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) ListTokens(context.Context, *ListTokensParams) (*TokenList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedMarketServiceServer) GetToken(context.Context, *GetTokenParams) (*Token, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedMarketServiceServer) ListTokenTrades(context.Context, *ListTokenTradesParams) (*TradeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTokenTrades not implemented")
}
func (UnimplementedMarketServiceServer) ListFollowingTrades(context.Context, *ListFollowingTradesParams) (*TradeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowingTrades not implemented")
}
func (UnimplementedMarketServiceServer) CollectTokens(context.Context, *CollectTokensParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectTokens not implemented")
}
func (UnimplementedMarketServiceServer) CollectTrades(context.Context, *CollectTradesParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectTrades not implemented")
}
func (UnimplementedMarketServiceServer) RunTask(context.Context, *RunTaskParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedMarketServiceServer) ListPublicFollowingWallets(context.Context, *ListPublicFollowingWalletsParams) (*WalletList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicFollowingWallets not implemented")
}
func (UnimplementedMarketServiceServer) UpdatePublicFollowingWallets(context.Context, *UpdatePublicFollowingWalletsParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePublicFollowingWallets not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokensParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListTokens(ctx, req.(*ListTokensParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetToken(ctx, req.(*GetTokenParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListTokenTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokenTradesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListTokenTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListTokenTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListTokenTrades(ctx, req.(*ListTokenTradesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListFollowingTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowingTradesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListFollowingTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListFollowingTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListFollowingTrades(ctx, req.(*ListFollowingTradesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_CollectTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectTokensParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CollectTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CollectTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CollectTokens(ctx, req.(*CollectTokensParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_CollectTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectTradesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CollectTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CollectTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CollectTrades(ctx, req.(*CollectTradesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTaskParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).RunTask(ctx, req.(*RunTaskParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ListPublicFollowingWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicFollowingWalletsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ListPublicFollowingWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ListPublicFollowingWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ListPublicFollowingWallets(ctx, req.(*ListPublicFollowingWalletsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_UpdatePublicFollowingWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePublicFollowingWalletsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).UpdatePublicFollowingWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_UpdatePublicFollowingWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).UpdatePublicFollowingWallets(ctx, req.(*UpdatePublicFollowingWalletsParams))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.dex.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTokens",
			Handler:    _MarketService_ListTokens_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _MarketService_GetToken_Handler,
		},
		{
			MethodName: "ListTokenTrades",
			Handler:    _MarketService_ListTokenTrades_Handler,
		},
		{
			MethodName: "ListFollowingTrades",
			Handler:    _MarketService_ListFollowingTrades_Handler,
		},
		{
			MethodName: "CollectTokens",
			Handler:    _MarketService_CollectTokens_Handler,
		},
		{
			MethodName: "CollectTrades",
			Handler:    _MarketService_CollectTrades_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _MarketService_RunTask_Handler,
		},
		{
			MethodName: "ListPublicFollowingWallets",
			Handler:    _MarketService_ListPublicFollowingWallets_Handler,
		},
		{
			MethodName: "UpdatePublicFollowingWallets",
			Handler:    _MarketService_UpdatePublicFollowingWallets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dex/market_service.proto",
}
