// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: counselor/counselor_service.proto

package counselorpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	_ "store/api/public/response"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCounselorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCounselorParams) Reset() {
	*x = ListCounselorParams{}
	mi := &file_counselor_counselor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCounselorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCounselorParams) ProtoMessage() {}

func (x *ListCounselorParams) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCounselorParams.ProtoReflect.Descriptor instead.
func (*ListCounselorParams) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{0}
}

type GetCounselorParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCounselorParams) Reset() {
	*x = GetCounselorParams{}
	mi := &file_counselor_counselor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCounselorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCounselorParams) ProtoMessage() {}

func (x *GetCounselorParams) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCounselorParams.ProtoReflect.Descriptor instead.
func (*GetCounselorParams) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCounselorParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CounselorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Counselor           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounselorList) Reset() {
	*x = CounselorList{}
	mi := &file_counselor_counselor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounselorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounselorList) ProtoMessage() {}

func (x *CounselorList) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounselorList.ProtoReflect.Descriptor instead.
func (*CounselorList) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{2}
}

func (x *CounselorList) GetList() []*Counselor {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CounselorList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CounselorList) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *CounselorList) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Counselor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,proto3" json:"_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Topics        []*Topic               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Desc          string                 `protobuf:"bytes,10,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Location      string                 `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	State         *Counselor_State       `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counselor) Reset() {
	*x = Counselor{}
	mi := &file_counselor_counselor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counselor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counselor) ProtoMessage() {}

func (x *Counselor) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counselor.ProtoReflect.Descriptor instead.
func (*Counselor) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{3}
}

func (x *Counselor) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Counselor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Counselor) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Counselor) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Counselor) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Counselor) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Counselor) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Counselor) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Counselor) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Counselor) GetState() *Counselor_State {
	if x != nil {
		return x.State
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_counselor_counselor_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{4}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_counselor_counselor_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{5}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Counselor_State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       int64                  `protobuf:"varint,1,opt,name=persons,proto3" json:"persons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counselor_State) Reset() {
	*x = Counselor_State{}
	mi := &file_counselor_counselor_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counselor_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counselor_State) ProtoMessage() {}

func (x *Counselor_State) ProtoReflect() protoreflect.Message {
	mi := &file_counselor_counselor_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counselor_State.ProtoReflect.Descriptor instead.
func (*Counselor_State) Descriptor() ([]byte, []int) {
	return file_counselor_counselor_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Counselor_State) GetPersons() int64 {
	if x != nil {
		return x.Persons
	}
	return 0
}

var File_counselor_counselor_service_proto protoreflect.FileDescriptor

const file_counselor_counselor_service_proto_rawDesc = "" +
	"\n" +
	"!counselor/counselor_service.proto\x12\rapi.counselor\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1epublic/response/response.proto\x1a\x17validate/validate.proto\"\x15\n" +
	"\x13ListCounselorParams\"$\n" +
	"\x12GetCounselorParams\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\rCounselorList\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.api.counselor.CounselorR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"\xdc\x02\n" +
	"\tCounselor\x12\x10\n" +
	"\x03_id\x18\x01 \x01(\tR\x03_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12,\n" +
	"\x06topics\x18\x04 \x03(\v2\x14.api.counselor.TopicR\x06topics\x12&\n" +
	"\x04tags\x18\x05 \x03(\v2\x12.api.counselor.TagR\x04tags\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x12\n" +
	"\x04desc\x18\n" +
	" \x01(\tR\x04desc\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\blocation\x18\f \x01(\tR\blocation\x124\n" +
	"\x05state\x18\r \x01(\v2\x1e.api.counselor.Counselor.StateR\x05state\x1a!\n" +
	"\x05State\x12\x18\n" +
	"\apersons\x18\x01 \x01(\x03R\apersons\"\x1b\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xf6\x01\n" +
	"\x10CounselorService\x12q\n" +
	"\x0eListCounselors\x12\".api.counselor.ListCounselorParams\x1a\x1c.api.counselor.CounselorList\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/cs/v1/counselors\x12o\n" +
	"\fGetCounselor\x12!.api.counselor.GetCounselorParams\x1a\x18.api.counselor.Counselor\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/cs/v1/counselors/{id}B!Z\x1fstore/api/counselor;counselorpbb\x06proto3"

var (
	file_counselor_counselor_service_proto_rawDescOnce sync.Once
	file_counselor_counselor_service_proto_rawDescData []byte
)

func file_counselor_counselor_service_proto_rawDescGZIP() []byte {
	file_counselor_counselor_service_proto_rawDescOnce.Do(func() {
		file_counselor_counselor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_counselor_counselor_service_proto_rawDesc), len(file_counselor_counselor_service_proto_rawDesc)))
	})
	return file_counselor_counselor_service_proto_rawDescData
}

var file_counselor_counselor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_counselor_counselor_service_proto_goTypes = []any{
	(*ListCounselorParams)(nil), // 0: api.counselor.ListCounselorParams
	(*GetCounselorParams)(nil),  // 1: api.counselor.GetCounselorParams
	(*CounselorList)(nil),       // 2: api.counselor.CounselorList
	(*Counselor)(nil),           // 3: api.counselor.Counselor
	(*Topic)(nil),               // 4: api.counselor.Topic
	(*Tag)(nil),                 // 5: api.counselor.Tag
	(*Counselor_State)(nil),     // 6: api.counselor.Counselor.State
}
var file_counselor_counselor_service_proto_depIdxs = []int32{
	3, // 0: api.counselor.CounselorList.list:type_name -> api.counselor.Counselor
	4, // 1: api.counselor.Counselor.topics:type_name -> api.counselor.Topic
	5, // 2: api.counselor.Counselor.tags:type_name -> api.counselor.Tag
	6, // 3: api.counselor.Counselor.state:type_name -> api.counselor.Counselor.State
	0, // 4: api.counselor.CounselorService.ListCounselors:input_type -> api.counselor.ListCounselorParams
	1, // 5: api.counselor.CounselorService.GetCounselor:input_type -> api.counselor.GetCounselorParams
	2, // 6: api.counselor.CounselorService.ListCounselors:output_type -> api.counselor.CounselorList
	3, // 7: api.counselor.CounselorService.GetCounselor:output_type -> api.counselor.Counselor
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_counselor_counselor_service_proto_init() }
func file_counselor_counselor_service_proto_init() {
	if File_counselor_counselor_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_counselor_counselor_service_proto_rawDesc), len(file_counselor_counselor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_counselor_counselor_service_proto_goTypes,
		DependencyIndexes: file_counselor_counselor_service_proto_depIdxs,
		MessageInfos:      file_counselor_counselor_service_proto_msgTypes,
	}.Build()
	File_counselor_counselor_service_proto = out.File
	file_counselor_counselor_service_proto_goTypes = nil
	file_counselor_counselor_service_proto_depIdxs = nil
}
