apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1024Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/displayName: clickhouse
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: clickhouse
  name: clickhouse
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  serviceName: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_ADMIN_PASSWORD
              value: pro@ClicKhouse
            - name: CLICKHOUSE_ADMIN_USER
              value: default
          image: bitnami/clickhouse
          imagePullPolicy: Always
          name: clickhouse
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 8123
              name: tcp
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /bitnami/clickhouse
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: clickhouse
  name: clickhouse
  namespace: prod
spec:
  ports:
    - port: 9000
      name: http
      protocol: TCP
      targetPort: 9000
    - port: 8123
      name: tcp
      protocol: TCP
      targetPort: 8123
  selector:
    app: clickhouse
  type: NodePort

