// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: usercenter/auth_service.proto

package ucpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	_ "store/api/public/response"
	_ "store/api/user/types"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAppleAuthTokenRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode string                 `protobuf:"bytes,1,opt,name=authorizationCode,proto3" json:"authorizationCode,omitempty"`
	Email             string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname          string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IdentityToken     string                 `protobuf:"bytes,4,opt,name=identityToken,proto3" json:"identityToken,omitempty"`
	RealUserStatus    uint32                 `protobuf:"varint,5,opt,name=realUserStatus,proto3" json:"realUserStatus,omitempty"`
	State             string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	User              string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAppleAuthTokenRequest) Reset() {
	*x = GetAppleAuthTokenRequest{}
	mi := &file_usercenter_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppleAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppleAuthTokenRequest) ProtoMessage() {}

func (x *GetAppleAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppleAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAppleAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_usercenter_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppleAuthTokenRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *GetAppleAuthTokenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAppleAuthTokenRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetAppleAuthTokenRequest) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

func (x *GetAppleAuthTokenRequest) GetRealUserStatus() uint32 {
	if x != nil {
		return x.RealUserStatus
	}
	return 0
}

func (x *GetAppleAuthTokenRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetAppleAuthTokenRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IsNew         bool                   `protobuf:"varint,2,opt,name=isNew,proto3" json:"isNew,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_usercenter_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_usercenter_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Token) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Token) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_usercenter_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_usercenter_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetTokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SendCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRequest) Reset() {
	*x = SendCodeRequest{}
	mi := &file_usercenter_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRequest) ProtoMessage() {}

func (x *SendCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercenter_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRequest.ProtoReflect.Descriptor instead.
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return file_usercenter_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_usercenter_auth_service_proto protoreflect.FileDescriptor

const file_usercenter_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1dusercenter/auth_service.proto\x12\x0eapi.usercenter\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x15user/types/user.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1epublic/response/response.proto\"\xf2\x01\n" +
	"\x18GetAppleAuthTokenRequest\x12,\n" +
	"\x11authorizationCode\x18\x01 \x01(\tR\x11authorizationCode\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12$\n" +
	"\ridentityToken\x18\x04 \x01(\tR\ridentityToken\x12&\n" +
	"\x0erealUserStatus\x18\x05 \x01(\rR\x0erealUserStatus\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\"K\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05isNew\x18\x02 \x01(\bR\x05isNew\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\";\n" +
	"\x0fGetTokenRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"'\n" +
	"\x0fSendCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone2\xd1\x02\n" +
	"\vAuthService\x12c\n" +
	"\bSendCode\x12\x1f.api.usercenter.SendCodeRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/usr/auth-codes\x12`\n" +
	"\bGetToken\x12\x1f.api.usercenter.GetTokenRequest\x1a\x15.api.usercenter.Token\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/usr/auth-tokens\x12{\n" +
	"\x11GetAppleAuthToken\x12(.api.usercenter.GetAppleAuthTokenRequest\x1a\x15.api.usercenter.Token\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/usr/v1/apple-auth-tokensB\x1bZ\x19store/api/usercenter;ucpbb\x06proto3"

var (
	file_usercenter_auth_service_proto_rawDescOnce sync.Once
	file_usercenter_auth_service_proto_rawDescData []byte
)

func file_usercenter_auth_service_proto_rawDescGZIP() []byte {
	file_usercenter_auth_service_proto_rawDescOnce.Do(func() {
		file_usercenter_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usercenter_auth_service_proto_rawDesc), len(file_usercenter_auth_service_proto_rawDesc)))
	})
	return file_usercenter_auth_service_proto_rawDescData
}

var file_usercenter_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_usercenter_auth_service_proto_goTypes = []any{
	(*GetAppleAuthTokenRequest)(nil), // 0: api.usercenter.GetAppleAuthTokenRequest
	(*Token)(nil),                    // 1: api.usercenter.Token
	(*GetTokenRequest)(nil),          // 2: api.usercenter.GetTokenRequest
	(*SendCodeRequest)(nil),          // 3: api.usercenter.SendCodeRequest
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
}
var file_usercenter_auth_service_proto_depIdxs = []int32{
	3, // 0: api.usercenter.AuthService.SendCode:input_type -> api.usercenter.SendCodeRequest
	2, // 1: api.usercenter.AuthService.GetToken:input_type -> api.usercenter.GetTokenRequest
	0, // 2: api.usercenter.AuthService.GetAppleAuthToken:input_type -> api.usercenter.GetAppleAuthTokenRequest
	4, // 3: api.usercenter.AuthService.SendCode:output_type -> google.protobuf.Empty
	1, // 4: api.usercenter.AuthService.GetToken:output_type -> api.usercenter.Token
	1, // 5: api.usercenter.AuthService.GetAppleAuthToken:output_type -> api.usercenter.Token
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usercenter_auth_service_proto_init() }
func file_usercenter_auth_service_proto_init() {
	if File_usercenter_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usercenter_auth_service_proto_rawDesc), len(file_usercenter_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usercenter_auth_service_proto_goTypes,
		DependencyIndexes: file_usercenter_auth_service_proto_depIdxs,
		MessageInfos:      file_usercenter_auth_service_proto_msgTypes,
	}.Build()
	File_usercenter_auth_service_proto = out.File
	file_usercenter_auth_service_proto_goTypes = nil
	file_usercenter_auth_service_proto_depIdxs = nil
}
