// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: voiceagent/motivation_service.proto

package voiceagent

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMotivationPosterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,2,opt,name=posterUrl,proto3" json:"posterUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMotivationPosterRequest) Reset() {
	*x = UpdateMotivationPosterRequest{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMotivationPosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMotivationPosterRequest) ProtoMessage() {}

func (x *UpdateMotivationPosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMotivationPosterRequest.ProtoReflect.Descriptor instead.
func (*UpdateMotivationPosterRequest) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMotivationPosterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMotivationPosterRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

type CreateMotivationCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 选用的音色 ID（通常是用户自己的克隆声音或指定的助理声音）
	AgentId string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	// 用户输入的激励关键词或灵感草稿内容
	OriginalText string `protobuf:"bytes,2,opt,name=originalText,proto3" json:"originalText,omitempty"`
	// 情感基调标签：例如 encouraging (激励), comfort (安慰), energetic (活力)
	EmotionTag string `protobuf:"bytes,3,opt,name=emotionTag,proto3" json:"emotionTag,omitempty"`
	// 指定的 TTS 模型 ID。
	// 建议参考: https://elevenlabs.io/docs/overview/models
	// - eleven_v3: 情感最丰富，适合激励场景。
	// - eleven_flash_v2_5: 低延迟，适合快速预览。
	ModelId string `protobuf:"bytes,4,opt,name=modelId,proto3" json:"modelId,omitempty"`
	// 背景氛围场景 ID（可选），用于为音频合成叠加特定的背景音乐
	SceneId string `protobuf:"bytes,5,opt,name=sceneId,proto3" json:"sceneId,omitempty"`
	// 是否生成公开分享链接
	IsPublic bool `protobuf:"varint,6,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	// 指定海报样式
	PosterStyle   string `protobuf:"bytes,7,opt,name=posterStyle,proto3" json:"posterStyle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMotivationCardRequest) Reset() {
	*x = CreateMotivationCardRequest{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMotivationCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMotivationCardRequest) ProtoMessage() {}

func (x *CreateMotivationCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMotivationCardRequest.ProtoReflect.Descriptor instead.
func (*CreateMotivationCardRequest) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMotivationCardRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateMotivationCardRequest) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *CreateMotivationCardRequest) GetEmotionTag() string {
	if x != nil {
		return x.EmotionTag
	}
	return ""
}

func (x *CreateMotivationCardRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CreateMotivationCardRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *CreateMotivationCardRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreateMotivationCardRequest) GetPosterStyle() string {
	if x != nil {
		return x.PosterStyle
	}
	return ""
}

type MotivationCardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 生成后的记录 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 合成并存储后的音频 URL
	AudioUrl string `protobuf:"bytes,2,opt,name=audioUrl,proto3" json:"audioUrl,omitempty"`
	// 专供社交分享的专属 H5 链接
	ShareUrl string `protobuf:"bytes,3,opt,name=shareUrl,proto3" json:"shareUrl,omitempty"`
	// 经过 AI 优化后的最终润色文案
	PolishedText string `protobuf:"bytes,4,opt,name=polishedText,proto3" json:"polishedText,omitempty"`
	// 额外提供给前端生成海报的信息
	User          *User     `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Agent         *Agent    `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	EmotionTag    string    `protobuf:"bytes,9,opt,name=emotionTag,proto3" json:"emotionTag,omitempty"`
	CreatedAt     int64     `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Waveform      []float32 `protobuf:"fixed32,11,rep,packed,name=waveform,proto3" json:"waveform,omitempty"`
	PosterStyle   string    `protobuf:"bytes,12,opt,name=posterStyle,proto3" json:"posterStyle,omitempty"`
	PosterUrl     string    `protobuf:"bytes,13,opt,name=posterUrl,proto3" json:"posterUrl,omitempty"`
	QrCodeUrl     string    `protobuf:"bytes,14,opt,name=qrCodeUrl,proto3" json:"qrCodeUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotivationCardResponse) Reset() {
	*x = MotivationCardResponse{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotivationCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotivationCardResponse) ProtoMessage() {}

func (x *MotivationCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotivationCardResponse.ProtoReflect.Descriptor instead.
func (*MotivationCardResponse) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{2}
}

func (x *MotivationCardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MotivationCardResponse) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *MotivationCardResponse) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *MotivationCardResponse) GetPolishedText() string {
	if x != nil {
		return x.PolishedText
	}
	return ""
}

func (x *MotivationCardResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MotivationCardResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *MotivationCardResponse) GetEmotionTag() string {
	if x != nil {
		return x.EmotionTag
	}
	return ""
}

func (x *MotivationCardResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MotivationCardResponse) GetWaveform() []float32 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

func (x *MotivationCardResponse) GetPosterStyle() string {
	if x != nil {
		return x.PosterStyle
	}
	return ""
}

func (x *MotivationCardResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *MotivationCardResponse) GetQrCodeUrl() string {
	if x != nil {
		return x.QrCodeUrl
	}
	return ""
}

type GetMotivationCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMotivationCardRequest) Reset() {
	*x = GetMotivationCardRequest{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMotivationCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMotivationCardRequest) ProtoMessage() {}

func (x *GetMotivationCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMotivationCardRequest.ProtoReflect.Descriptor instead.
func (*GetMotivationCardRequest) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMotivationCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMotivationCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMotivationCardsRequest) Reset() {
	*x = ListMotivationCardsRequest{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMotivationCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMotivationCardsRequest) ProtoMessage() {}

func (x *ListMotivationCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMotivationCardsRequest.ProtoReflect.Descriptor instead.
func (*ListMotivationCardsRequest) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListMotivationCardsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMotivationCardsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MotivationCardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MotivationCard      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotivationCardList) Reset() {
	*x = MotivationCardList{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotivationCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotivationCardList) ProtoMessage() {}

func (x *MotivationCardList) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotivationCardList.ProtoReflect.Descriptor instead.
func (*MotivationCardList) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{5}
}

func (x *MotivationCardList) GetList() []*MotivationCard {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MotivationCardList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteMotivationCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMotivationCardRequest) Reset() {
	*x = DeleteMotivationCardRequest{}
	mi := &file_voiceagent_motivation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMotivationCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMotivationCardRequest) ProtoMessage() {}

func (x *DeleteMotivationCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voiceagent_motivation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMotivationCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteMotivationCardRequest) Descriptor() ([]byte, []int) {
	return file_voiceagent_motivation_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMotivationCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_voiceagent_motivation_service_proto protoreflect.FileDescriptor

const file_voiceagent_motivation_service_proto_rawDesc = "" +
	"\n" +
	"#voiceagent/motivation_service.proto\x12\x0eapi.voiceagent\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\x1a\x1bvoiceagent/motivation.proto\x1a\x16voiceagent/agent.proto\"_\n" +
	"\x1dUpdateMotivationPosterRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12%\n" +
	"\tposterUrl\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tposterUrl\"\xff\x01\n" +
	"\x1bCreateMotivationCardRequest\x12!\n" +
	"\aagentId\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aagentId\x12+\n" +
	"\foriginalText\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\foriginalText\x12\x1e\n" +
	"\n" +
	"emotionTag\x18\x03 \x01(\tR\n" +
	"emotionTag\x12\x18\n" +
	"\amodelId\x18\x04 \x01(\tR\amodelId\x12\x18\n" +
	"\asceneId\x18\x05 \x01(\tR\asceneId\x12\x1a\n" +
	"\bisPublic\x18\x06 \x01(\bR\bisPublic\x12 \n" +
	"\vposterStyle\x18\a \x01(\tR\vposterStyle\"\x93\x03\n" +
	"\x16MotivationCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\baudioUrl\x18\x02 \x01(\tR\baudioUrl\x12\x1a\n" +
	"\bshareUrl\x18\x03 \x01(\tR\bshareUrl\x12\"\n" +
	"\fpolishedText\x18\x04 \x01(\tR\fpolishedText\x12(\n" +
	"\x04user\x18\x05 \x01(\v2\x14.api.voiceagent.UserR\x04user\x12+\n" +
	"\x05agent\x18\a \x01(\v2\x15.api.voiceagent.AgentR\x05agent\x12\x1e\n" +
	"\n" +
	"emotionTag\x18\t \x01(\tR\n" +
	"emotionTag\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bwaveform\x18\v \x03(\x02R\bwaveform\x12 \n" +
	"\vposterStyle\x18\f \x01(\tR\vposterStyle\x12\x1c\n" +
	"\tposterUrl\x18\r \x01(\tR\tposterUrl\x12\x1c\n" +
	"\tqrCodeUrl\x18\x0e \x01(\tR\tqrCodeUrl\"3\n" +
	"\x18GetMotivationCardRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"D\n" +
	"\x1aListMotivationCardsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"^\n" +
	"\x12MotivationCardList\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.api.voiceagent.MotivationCardR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"6\n" +
	"\x1bDeleteMotivationCardRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id2\xb4\x05\n" +
	"\x11MotivationService\x12\x8b\x01\n" +
	"\x14CreateMotivationCard\x12+.api.voiceagent.CreateMotivationCardRequest\x1a&.api.voiceagent.MotivationCardResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/va/motivations\x12\x7f\n" +
	"\x11GetMotivationCard\x12(.api.voiceagent.GetMotivationCardRequest\x1a\x1e.api.voiceagent.MotivationCard\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/va/motivations/{id}\x12\x82\x01\n" +
	"\x13ListMotivationCards\x12*.api.voiceagent.ListMotivationCardsRequest\x1a\".api.voiceagent.MotivationCardList\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/va/motivations\x12}\n" +
	"\x14DeleteMotivationCard\x12+.api.voiceagent.DeleteMotivationCardRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/va/motivations/{id}\x12\x8b\x01\n" +
	"\x16UpdateMotivationPoster\x12-.api.voiceagent.UpdateMotivationPosterRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*2\x1f/api/va/motivations/{id}/posterB!Z\x1fstore/api/voiceagent;voiceagentb\x06proto3"

var (
	file_voiceagent_motivation_service_proto_rawDescOnce sync.Once
	file_voiceagent_motivation_service_proto_rawDescData []byte
)

func file_voiceagent_motivation_service_proto_rawDescGZIP() []byte {
	file_voiceagent_motivation_service_proto_rawDescOnce.Do(func() {
		file_voiceagent_motivation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voiceagent_motivation_service_proto_rawDesc), len(file_voiceagent_motivation_service_proto_rawDesc)))
	})
	return file_voiceagent_motivation_service_proto_rawDescData
}

var file_voiceagent_motivation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_voiceagent_motivation_service_proto_goTypes = []any{
	(*UpdateMotivationPosterRequest)(nil), // 0: api.voiceagent.UpdateMotivationPosterRequest
	(*CreateMotivationCardRequest)(nil),   // 1: api.voiceagent.CreateMotivationCardRequest
	(*MotivationCardResponse)(nil),        // 2: api.voiceagent.MotivationCardResponse
	(*GetMotivationCardRequest)(nil),      // 3: api.voiceagent.GetMotivationCardRequest
	(*ListMotivationCardsRequest)(nil),    // 4: api.voiceagent.ListMotivationCardsRequest
	(*MotivationCardList)(nil),            // 5: api.voiceagent.MotivationCardList
	(*DeleteMotivationCardRequest)(nil),   // 6: api.voiceagent.DeleteMotivationCardRequest
	(*User)(nil),                          // 7: api.voiceagent.User
	(*Agent)(nil),                         // 8: api.voiceagent.Agent
	(*MotivationCard)(nil),                // 9: api.voiceagent.MotivationCard
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
}
var file_voiceagent_motivation_service_proto_depIdxs = []int32{
	7,  // 0: api.voiceagent.MotivationCardResponse.user:type_name -> api.voiceagent.User
	8,  // 1: api.voiceagent.MotivationCardResponse.agent:type_name -> api.voiceagent.Agent
	9,  // 2: api.voiceagent.MotivationCardList.list:type_name -> api.voiceagent.MotivationCard
	1,  // 3: api.voiceagent.MotivationService.CreateMotivationCard:input_type -> api.voiceagent.CreateMotivationCardRequest
	3,  // 4: api.voiceagent.MotivationService.GetMotivationCard:input_type -> api.voiceagent.GetMotivationCardRequest
	4,  // 5: api.voiceagent.MotivationService.ListMotivationCards:input_type -> api.voiceagent.ListMotivationCardsRequest
	6,  // 6: api.voiceagent.MotivationService.DeleteMotivationCard:input_type -> api.voiceagent.DeleteMotivationCardRequest
	0,  // 7: api.voiceagent.MotivationService.UpdateMotivationPoster:input_type -> api.voiceagent.UpdateMotivationPosterRequest
	2,  // 8: api.voiceagent.MotivationService.CreateMotivationCard:output_type -> api.voiceagent.MotivationCardResponse
	9,  // 9: api.voiceagent.MotivationService.GetMotivationCard:output_type -> api.voiceagent.MotivationCard
	5,  // 10: api.voiceagent.MotivationService.ListMotivationCards:output_type -> api.voiceagent.MotivationCardList
	10, // 11: api.voiceagent.MotivationService.DeleteMotivationCard:output_type -> google.protobuf.Empty
	10, // 12: api.voiceagent.MotivationService.UpdateMotivationPoster:output_type -> google.protobuf.Empty
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_voiceagent_motivation_service_proto_init() }
func file_voiceagent_motivation_service_proto_init() {
	if File_voiceagent_motivation_service_proto != nil {
		return
	}
	file_voiceagent_motivation_proto_init()
	file_voiceagent_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voiceagent_motivation_service_proto_rawDesc), len(file_voiceagent_motivation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voiceagent_motivation_service_proto_goTypes,
		DependencyIndexes: file_voiceagent_motivation_service_proto_depIdxs,
		MessageInfos:      file_voiceagent_motivation_service_proto_msgTypes,
	}.Build()
	File_voiceagent_motivation_service_proto = out.File
	file_voiceagent_motivation_service_proto_goTypes = nil
	file_voiceagent_motivation_service_proto_depIdxs = nil
}
