// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: databank/databank.proto

package databankpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddFilesParams with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddFilesParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddFilesParams with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddFilesParamsMultiError,
// or nil if none found.
func (m *AddFilesParams) ValidateAll() error {
	return m.validate(true)
}

func (m *AddFilesParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Public

	// no validation rules for Source

	if len(errors) > 0 {
		return AddFilesParamsMultiError(errors)
	}

	return nil
}

// AddFilesParamsMultiError is an error wrapping multiple validation errors
// returned by AddFilesParams.ValidateAll() if the designated constraints
// aren't met.
type AddFilesParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddFilesParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddFilesParamsMultiError) AllErrors() []error { return m }

// AddFilesParamsValidationError is the validation error returned by
// AddFilesParams.Validate if the designated constraints aren't met.
type AddFilesParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddFilesParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddFilesParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddFilesParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddFilesParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddFilesParamsValidationError) ErrorName() string { return "AddFilesParamsValidationError" }

// Error satisfies the builtin error interface
func (e AddFilesParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddFilesParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddFilesParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddFilesParamsValidationError{}

// Validate checks the field values on ListUserAssetsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserAssetsParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserAssetsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserAssetsParamsMultiError, or nil if none found.
func (m *ListUserAssetsParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserAssetsParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	if len(errors) > 0 {
		return ListUserAssetsParamsMultiError(errors)
	}

	return nil
}

// ListUserAssetsParamsMultiError is an error wrapping multiple validation
// errors returned by ListUserAssetsParams.ValidateAll() if the designated
// constraints aren't met.
type ListUserAssetsParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserAssetsParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserAssetsParamsMultiError) AllErrors() []error { return m }

// ListUserAssetsParamsValidationError is the validation error returned by
// ListUserAssetsParams.Validate if the designated constraints aren't met.
type ListUserAssetsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserAssetsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserAssetsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserAssetsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserAssetsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserAssetsParamsValidationError) ErrorName() string {
	return "ListUserAssetsParamsValidationError"
}

// Error satisfies the builtin error interface
func (e ListUserAssetsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUserAssetsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUserAssetsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserAssetsParamsValidationError{}

// Validate checks the field values on ListAssetsParams with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAssetsParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAssetsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAssetsParamsMultiError, or nil if none found.
func (m *ListAssetsParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAssetsParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Status

	// no validation rules for UserId

	if len(errors) > 0 {
		return ListAssetsParamsMultiError(errors)
	}

	return nil
}

// ListAssetsParamsMultiError is an error wrapping multiple validation errors
// returned by ListAssetsParams.ValidateAll() if the designated constraints
// aren't met.
type ListAssetsParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAssetsParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAssetsParamsMultiError) AllErrors() []error { return m }

// ListAssetsParamsValidationError is the validation error returned by
// ListAssetsParams.Validate if the designated constraints aren't met.
type ListAssetsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAssetsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAssetsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAssetsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAssetsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAssetsParamsValidationError) ErrorName() string { return "ListAssetsParamsValidationError" }

// Error satisfies the builtin error interface
func (e ListAssetsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAssetsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAssetsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAssetsParamsValidationError{}

// Validate checks the field values on ListAssetsResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAssetsResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAssetsResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAssetsResultMultiError, or nil if none found.
func (m *ListAssetsResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAssetsResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Total

	for idx, item := range m.GetAssets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAssetsResultValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAssetsResultValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAssetsResultValidationError{
					field:  fmt.Sprintf("Assets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAssetsResultMultiError(errors)
	}

	return nil
}

// ListAssetsResultMultiError is an error wrapping multiple validation errors
// returned by ListAssetsResult.ValidateAll() if the designated constraints
// aren't met.
type ListAssetsResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAssetsResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAssetsResultMultiError) AllErrors() []error { return m }

// ListAssetsResultValidationError is the validation error returned by
// ListAssetsResult.Validate if the designated constraints aren't met.
type ListAssetsResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAssetsResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAssetsResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAssetsResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAssetsResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAssetsResultValidationError) ErrorName() string { return "ListAssetsResultValidationError" }

// Error satisfies the builtin error interface
func (e ListAssetsResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAssetsResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAssetsResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAssetsResultValidationError{}

// Validate checks the field values on AddFilesResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddFilesResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddFilesResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddFilesResultMultiError,
// or nil if none found.
func (m *AddFilesResult) ValidateAll() error {
	return m.validate(true)
}

func (m *AddFilesResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetFiles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddFilesResultValidationError{
						field:  fmt.Sprintf("Files[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddFilesResultValidationError{
						field:  fmt.Sprintf("Files[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddFilesResultValidationError{
					field:  fmt.Sprintf("Files[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AddFilesResultMultiError(errors)
	}

	return nil
}

// AddFilesResultMultiError is an error wrapping multiple validation errors
// returned by AddFilesResult.ValidateAll() if the designated constraints
// aren't met.
type AddFilesResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddFilesResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddFilesResultMultiError) AllErrors() []error { return m }

// AddFilesResultValidationError is the validation error returned by
// AddFilesResult.Validate if the designated constraints aren't met.
type AddFilesResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddFilesResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddFilesResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddFilesResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddFilesResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddFilesResultValidationError) ErrorName() string { return "AddFilesResultValidationError" }

// Error satisfies the builtin error interface
func (e AddFilesResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddFilesResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddFilesResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddFilesResultValidationError{}

// Validate checks the field values on AddAssetsParams with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddAssetsParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddAssetsParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddAssetsParamsMultiError, or nil if none found.
func (m *AddAssetsParams) ValidateAll() error {
	return m.validate(true)
}

func (m *AddAssetsParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAssets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddAssetsParamsValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddAssetsParamsValidationError{
						field:  fmt.Sprintf("Assets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddAssetsParamsValidationError{
					field:  fmt.Sprintf("Assets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AddAssetsParamsMultiError(errors)
	}

	return nil
}

// AddAssetsParamsMultiError is an error wrapping multiple validation errors
// returned by AddAssetsParams.ValidateAll() if the designated constraints
// aren't met.
type AddAssetsParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddAssetsParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddAssetsParamsMultiError) AllErrors() []error { return m }

// AddAssetsParamsValidationError is the validation error returned by
// AddAssetsParams.Validate if the designated constraints aren't met.
type AddAssetsParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddAssetsParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddAssetsParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddAssetsParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddAssetsParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddAssetsParamsValidationError) ErrorName() string { return "AddAssetsParamsValidationError" }

// Error satisfies the builtin error interface
func (e AddAssetsParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddAssetsParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddAssetsParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddAssetsParamsValidationError{}
