// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: mgmt/user.proto

package mgmtpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_GetUsersSummary_FullMethodName        = "/api.mgmt.User/GetUsersSummary"
	User_ListUsers_FullMethodName              = "/api.mgmt.User/ListUsers"
	User_UpdateUser_FullMethodName             = "/api.mgmt.User/UpdateUser"
	User_AddUserMemberSubscribe_FullMethodName = "/api.mgmt.User/AddUserMemberSubscribe"
	User_GetMemberUsageState_FullMethodName    = "/api.mgmt.User/GetMemberUsageState"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	GetUsersSummary(ctx context.Context, in *GetUsersSummaryParams, opts ...grpc.CallOption) (*UsersSummary, error)
	ListUsers(ctx context.Context, in *ListUsersParams, opts ...grpc.CallOption) (*ListUsersResult, error)
	UpdateUser(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddUserMemberSubscribe(ctx context.Context, in *AddUserMemberSubscribeParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMemberUsageState(ctx context.Context, in *GetMemberUsageStateParams, opts ...grpc.CallOption) (*GetMemberUsageStateResult, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUsersSummary(ctx context.Context, in *GetUsersSummaryParams, opts ...grpc.CallOption) (*UsersSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersSummary)
	err := c.cc.Invoke(ctx, User_GetUsersSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ListUsers(ctx context.Context, in *ListUsersParams, opts ...grpc.CallOption) (*ListUsersResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResult)
	err := c.cc.Invoke(ctx, User_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddUserMemberSubscribe(ctx context.Context, in *AddUserMemberSubscribeParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_AddUserMemberSubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetMemberUsageState(ctx context.Context, in *GetMemberUsageStateParams, opts ...grpc.CallOption) (*GetMemberUsageStateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberUsageStateResult)
	err := c.cc.Invoke(ctx, User_GetMemberUsageState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	GetUsersSummary(context.Context, *GetUsersSummaryParams) (*UsersSummary, error)
	ListUsers(context.Context, *ListUsersParams) (*ListUsersResult, error)
	UpdateUser(context.Context, *UpdateUserParams) (*emptypb.Empty, error)
	AddUserMemberSubscribe(context.Context, *AddUserMemberSubscribeParams) (*emptypb.Empty, error)
	GetMemberUsageState(context.Context, *GetMemberUsageStateParams) (*GetMemberUsageStateResult, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) GetUsersSummary(context.Context, *GetUsersSummaryParams) (*UsersSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersSummary not implemented")
}
func (UnimplementedUserServer) ListUsers(context.Context, *ListUsersParams) (*ListUsersResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserServer) UpdateUser(context.Context, *UpdateUserParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServer) AddUserMemberSubscribe(context.Context, *AddUserMemberSubscribeParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserMemberSubscribe not implemented")
}
func (UnimplementedUserServer) GetMemberUsageState(context.Context, *GetMemberUsageStateParams) (*GetMemberUsageStateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberUsageState not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_GetUsersSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersSummaryParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUsersSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUsersSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUsersSummary(ctx, req.(*GetUsersSummaryParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ListUsers(ctx, req.(*ListUsersParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddUserMemberSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserMemberSubscribeParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUserMemberSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddUserMemberSubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUserMemberSubscribe(ctx, req.(*AddUserMemberSubscribeParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetMemberUsageState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberUsageStateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetMemberUsageState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetMemberUsageState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetMemberUsageState(ctx, req.(*GetMemberUsageStateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.mgmt.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsersSummary",
			Handler:    _User_GetUsersSummary_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _User_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "AddUserMemberSubscribe",
			Handler:    _User_AddUserMemberSubscribe_Handler,
		},
		{
			MethodName: "GetMemberUsageState",
			Handler:    _User_GetMemberUsageState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mgmt/user.proto",
}
