// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: mgmt/user.proto

package mgmtpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddUserMemberSubscribeParams with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddUserMemberSubscribeParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddUserMemberSubscribeParams with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddUserMemberSubscribeParamsMultiError, or nil if none found.
func (m *AddUserMemberSubscribeParams) ValidateAll() error {
	return m.validate(true)
}

func (m *AddUserMemberSubscribeParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Level

	// no validation rules for Cycle

	if len(errors) > 0 {
		return AddUserMemberSubscribeParamsMultiError(errors)
	}

	return nil
}

// AddUserMemberSubscribeParamsMultiError is an error wrapping multiple
// validation errors returned by AddUserMemberSubscribeParams.ValidateAll() if
// the designated constraints aren't met.
type AddUserMemberSubscribeParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddUserMemberSubscribeParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddUserMemberSubscribeParamsMultiError) AllErrors() []error { return m }

// AddUserMemberSubscribeParamsValidationError is the validation error returned
// by AddUserMemberSubscribeParams.Validate if the designated constraints
// aren't met.
type AddUserMemberSubscribeParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddUserMemberSubscribeParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddUserMemberSubscribeParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddUserMemberSubscribeParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddUserMemberSubscribeParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddUserMemberSubscribeParamsValidationError) ErrorName() string {
	return "AddUserMemberSubscribeParamsValidationError"
}

// Error satisfies the builtin error interface
func (e AddUserMemberSubscribeParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddUserMemberSubscribeParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddUserMemberSubscribeParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddUserMemberSubscribeParamsValidationError{}

// Validate checks the field values on UsersSummary with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UsersSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UsersSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UsersSummaryMultiError, or
// nil if none found.
func (m *UsersSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *UsersSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalCount

	// no validation rules for TodayCount

	if len(errors) > 0 {
		return UsersSummaryMultiError(errors)
	}

	return nil
}

// UsersSummaryMultiError is an error wrapping multiple validation errors
// returned by UsersSummary.ValidateAll() if the designated constraints aren't met.
type UsersSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsersSummaryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsersSummaryMultiError) AllErrors() []error { return m }

// UsersSummaryValidationError is the validation error returned by
// UsersSummary.Validate if the designated constraints aren't met.
type UsersSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsersSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsersSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsersSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsersSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsersSummaryValidationError) ErrorName() string { return "UsersSummaryValidationError" }

// Error satisfies the builtin error interface
func (e UsersSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsersSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsersSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsersSummaryValidationError{}

// Validate checks the field values on GetUsersSummaryParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUsersSummaryParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUsersSummaryParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUsersSummaryParamsMultiError, or nil if none found.
func (m *GetUsersSummaryParams) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUsersSummaryParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUsersSummaryParamsMultiError(errors)
	}

	return nil
}

// GetUsersSummaryParamsMultiError is an error wrapping multiple validation
// errors returned by GetUsersSummaryParams.ValidateAll() if the designated
// constraints aren't met.
type GetUsersSummaryParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUsersSummaryParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUsersSummaryParamsMultiError) AllErrors() []error { return m }

// GetUsersSummaryParamsValidationError is the validation error returned by
// GetUsersSummaryParams.Validate if the designated constraints aren't met.
type GetUsersSummaryParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUsersSummaryParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUsersSummaryParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUsersSummaryParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUsersSummaryParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUsersSummaryParamsValidationError) ErrorName() string {
	return "GetUsersSummaryParamsValidationError"
}

// Error satisfies the builtin error interface
func (e GetUsersSummaryParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUsersSummaryParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUsersSummaryParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUsersSummaryParamsValidationError{}

// Validate checks the field values on UpdateUserParams with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserParamsMultiError, or nil if none found.
func (m *UpdateUserParams) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Action

	if all {
		switch v := interface{}(m.GetValues()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateUserParamsValidationError{
					field:  "Values",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateUserParamsValidationError{
					field:  "Values",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValues()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateUserParamsValidationError{
				field:  "Values",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateUserParamsMultiError(errors)
	}

	return nil
}

// UpdateUserParamsMultiError is an error wrapping multiple validation errors
// returned by UpdateUserParams.ValidateAll() if the designated constraints
// aren't met.
type UpdateUserParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserParamsMultiError) AllErrors() []error { return m }

// UpdateUserParamsValidationError is the validation error returned by
// UpdateUserParams.Validate if the designated constraints aren't met.
type UpdateUserParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserParamsValidationError) ErrorName() string { return "UpdateUserParamsValidationError" }

// Error satisfies the builtin error interface
func (e UpdateUserParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserParamsValidationError{}

// Validate checks the field values on GetMemberUsageStateParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMemberUsageStateParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMemberUsageStateParams with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMemberUsageStateParamsMultiError, or nil if none found.
func (m *GetMemberUsageStateParams) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMemberUsageStateParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetUserIdOrEmail()) < 1 {
		err := GetMemberUsageStateParamsValidationError{
			field:  "UserIdOrEmail",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetMemberUsageStateParamsMultiError(errors)
	}

	return nil
}

// GetMemberUsageStateParamsMultiError is an error wrapping multiple validation
// errors returned by GetMemberUsageStateParams.ValidateAll() if the
// designated constraints aren't met.
type GetMemberUsageStateParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMemberUsageStateParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMemberUsageStateParamsMultiError) AllErrors() []error { return m }

// GetMemberUsageStateParamsValidationError is the validation error returned by
// GetMemberUsageStateParams.Validate if the designated constraints aren't met.
type GetMemberUsageStateParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMemberUsageStateParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMemberUsageStateParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMemberUsageStateParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMemberUsageStateParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMemberUsageStateParamsValidationError) ErrorName() string {
	return "GetMemberUsageStateParamsValidationError"
}

// Error satisfies the builtin error interface
func (e GetMemberUsageStateParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMemberUsageStateParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMemberUsageStateParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMemberUsageStateParamsValidationError{}

// Validate checks the field values on GetMemberUsageStateResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMemberUsageStateResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMemberUsageStateResult with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMemberUsageStateResultMultiError, or nil if none found.
func (m *GetMemberUsageStateResult) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMemberUsageStateResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetState()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMemberUsageStateResultValidationError{
					field:  "State",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMemberUsageStateResultValidationError{
					field:  "State",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetState()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMemberUsageStateResultValidationError{
				field:  "State",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMemberUsageStateResultMultiError(errors)
	}

	return nil
}

// GetMemberUsageStateResultMultiError is an error wrapping multiple validation
// errors returned by GetMemberUsageStateResult.ValidateAll() if the
// designated constraints aren't met.
type GetMemberUsageStateResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMemberUsageStateResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMemberUsageStateResultMultiError) AllErrors() []error { return m }

// GetMemberUsageStateResultValidationError is the validation error returned by
// GetMemberUsageStateResult.Validate if the designated constraints aren't met.
type GetMemberUsageStateResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMemberUsageStateResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMemberUsageStateResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMemberUsageStateResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMemberUsageStateResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMemberUsageStateResultValidationError) ErrorName() string {
	return "GetMemberUsageStateResultValidationError"
}

// Error satisfies the builtin error interface
func (e GetMemberUsageStateResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMemberUsageStateResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMemberUsageStateResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMemberUsageStateResultValidationError{}

// Validate checks the field values on ListUsersParams with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListUsersParams) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsersParams with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUsersParamsMultiError, or nil if none found.
func (m *ListUsersParams) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsersParams) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Status

	// no validation rules for Keyword

	if len(errors) > 0 {
		return ListUsersParamsMultiError(errors)
	}

	return nil
}

// ListUsersParamsMultiError is an error wrapping multiple validation errors
// returned by ListUsersParams.ValidateAll() if the designated constraints
// aren't met.
type ListUsersParamsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsersParamsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsersParamsMultiError) AllErrors() []error { return m }

// ListUsersParamsValidationError is the validation error returned by
// ListUsersParams.Validate if the designated constraints aren't met.
type ListUsersParamsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsersParamsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsersParamsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsersParamsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsersParamsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsersParamsValidationError) ErrorName() string { return "ListUsersParamsValidationError" }

// Error satisfies the builtin error interface
func (e ListUsersParamsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsersParams.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsersParamsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsersParamsValidationError{}

// Validate checks the field values on ListUsersResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListUsersResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsersResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUsersResultMultiError, or nil if none found.
func (m *ListUsersResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsersResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Size

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListUsersResultValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListUsersResultValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListUsersResultValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListUsersResultMultiError(errors)
	}

	return nil
}

// ListUsersResultMultiError is an error wrapping multiple validation errors
// returned by ListUsersResult.ValidateAll() if the designated constraints
// aren't met.
type ListUsersResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsersResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsersResultMultiError) AllErrors() []error { return m }

// ListUsersResultValidationError is the validation error returned by
// ListUsersResult.Validate if the designated constraints aren't met.
type ListUsersResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsersResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsersResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsersResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsersResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsersResultValidationError) ErrorName() string { return "ListUsersResultValidationError" }

// Error satisfies the builtin error interface
func (e ListUsersResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsersResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsersResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsersResultValidationError{}

// Validate checks the field values on UpdateUserParams_Values with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserParams_Values) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserParams_Values with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserParams_ValuesMultiError, or nil if none found.
func (m *UpdateUserParams_Values) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserParams_Values) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	if len(errors) > 0 {
		return UpdateUserParams_ValuesMultiError(errors)
	}

	return nil
}

// UpdateUserParams_ValuesMultiError is an error wrapping multiple validation
// errors returned by UpdateUserParams_Values.ValidateAll() if the designated
// constraints aren't met.
type UpdateUserParams_ValuesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserParams_ValuesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserParams_ValuesMultiError) AllErrors() []error { return m }

// UpdateUserParams_ValuesValidationError is the validation error returned by
// UpdateUserParams_Values.Validate if the designated constraints aren't met.
type UpdateUserParams_ValuesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserParams_ValuesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserParams_ValuesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserParams_ValuesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserParams_ValuesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserParams_ValuesValidationError) ErrorName() string {
	return "UpdateUserParams_ValuesValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserParams_ValuesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserParams_Values.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserParams_ValuesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserParams_ValuesValidationError{}
