// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: mgmt/user.proto

package mgmtpb

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserAddUserMemberSubscribe = "/api.mgmt.User/AddUserMemberSubscribe"
const OperationUserGetMemberUsageState = "/api.mgmt.User/GetMemberUsageState"
const OperationUserGetUsersSummary = "/api.mgmt.User/GetUsersSummary"
const OperationUserListUsers = "/api.mgmt.User/ListUsers"
const OperationUserUpdateUser = "/api.mgmt.User/UpdateUser"

type UserHTTPServer interface {
	AddUserMemberSubscribe(context.Context, *AddUserMemberSubscribeParams) (*emptypb.Empty, error)
	GetMemberUsageState(context.Context, *GetMemberUsageStateParams) (*GetMemberUsageStateResult, error)
	GetUsersSummary(context.Context, *GetUsersSummaryParams) (*UsersSummary, error)
	ListUsers(context.Context, *ListUsersParams) (*ListUsersResult, error)
	UpdateUser(context.Context, *UpdateUserParams) (*emptypb.Empty, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.GET("/api/mgmt/user-summary", _User_GetUsersSummary0_HTTP_Handler(srv))
	r.GET("/api/mgmt/users", _User_ListUsers0_HTTP_Handler(srv))
	r.PATCH("/api/mgmt/users", _User_UpdateUser1_HTTP_Handler(srv))
	r.POST("/api/mgmt/users/{id}/member-subscribes", _User_AddUserMemberSubscribe0_HTTP_Handler(srv))
	r.GET("/api/mgmt/users/{userIdOrEmail}/usage-states", _User_GetMemberUsageState0_HTTP_Handler(srv))
}

func _User_GetUsersSummary0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUsersSummaryParams
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserGetUsersSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUsersSummary(ctx, req.(*GetUsersSummaryParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UsersSummary)
		return ctx.Result(200, reply)
	}
}

func _User_ListUsers0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersParams
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResult)
		return ctx.Result(200, reply)
	}
}

func _User_UpdateUser1_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserParams
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUpdateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUser(ctx, req.(*UpdateUserParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _User_AddUserMemberSubscribe0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddUserMemberSubscribeParams
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserAddUserMemberSubscribe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddUserMemberSubscribe(ctx, req.(*AddUserMemberSubscribeParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _User_GetMemberUsageState0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMemberUsageStateParams
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserGetMemberUsageState)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMemberUsageState(ctx, req.(*GetMemberUsageStateParams))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMemberUsageStateResult)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	AddUserMemberSubscribe(ctx context.Context, req *AddUserMemberSubscribeParams, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetMemberUsageState(ctx context.Context, req *GetMemberUsageStateParams, opts ...http.CallOption) (rsp *GetMemberUsageStateResult, err error)
	GetUsersSummary(ctx context.Context, req *GetUsersSummaryParams, opts ...http.CallOption) (rsp *UsersSummary, err error)
	ListUsers(ctx context.Context, req *ListUsersParams, opts ...http.CallOption) (rsp *ListUsersResult, err error)
	UpdateUser(ctx context.Context, req *UpdateUserParams, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

func (c *UserHTTPClientImpl) AddUserMemberSubscribe(ctx context.Context, in *AddUserMemberSubscribeParams, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/mgmt/users/{id}/member-subscribes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserAddUserMemberSubscribe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserHTTPClientImpl) GetMemberUsageState(ctx context.Context, in *GetMemberUsageStateParams, opts ...http.CallOption) (*GetMemberUsageStateResult, error) {
	var out GetMemberUsageStateResult
	pattern := "/api/mgmt/users/{userIdOrEmail}/usage-states"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserGetMemberUsageState))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserHTTPClientImpl) GetUsersSummary(ctx context.Context, in *GetUsersSummaryParams, opts ...http.CallOption) (*UsersSummary, error) {
	var out UsersSummary
	pattern := "/api/mgmt/user-summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserGetUsersSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersParams, opts ...http.CallOption) (*ListUsersResult, error) {
	var out ListUsersResult
	pattern := "/api/mgmt/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UserHTTPClientImpl) UpdateUser(ctx context.Context, in *UpdateUserParams, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/mgmt/users"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserUpdateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
